# Generated by rdeck: do not edit by hand
# deck.gl version: 8.3.7

#' @rdname arc_layer
#' @autoglobal
#' @export
add_arc_layer <- function(rdeck,
                          ...,
                          id = "ArcLayer",
                          data = NULL,
                          visible = TRUE,
                          pickable = FALSE,
                          opacity = 1,
                          position_format = "XYZ",
                          color_format = "RGBA",
                          auto_highlight = FALSE,
                          highlight_color = "#00008080",
                          get_source_position = source_position,
                          get_target_position = target_position,
                          get_source_color = "#000000ff",
                          get_target_color = "#000000ff",
                          get_width = 1,
                          get_height = 1,
                          get_tilt = 0,
                          great_circle = FALSE,
                          width_units = "pixels",
                          width_scale = 1,
                          width_min_pixels = 0,
                          width_max_pixels = 9007199254740991,
                          tooltip = FALSE) {
  arc_layer <- layer(
    rdeck,
    ...,
    type = "ArcLayer",
    data = data,
    visible = visible,
    pickable = pickable,
    opacity = opacity,
    position_format = position_format,
    color_format = color_format,
    auto_highlight = auto_highlight,
    highlight_color = accessor(rlang::enquo(highlight_color), data),
    get_source_position = accessor(rlang::enquo(get_source_position), data),
    get_target_position = accessor(rlang::enquo(get_target_position), data),
    get_source_color = accessor(rlang::enquo(get_source_color), data),
    get_target_color = accessor(rlang::enquo(get_target_color), data),
    get_width = accessor_scale(rlang::enquo(get_width), data),
    get_height = accessor_scale(rlang::enquo(get_height), data),
    get_tilt = accessor(rlang::enquo(get_tilt), data),
    great_circle = great_circle,
    width_units = width_units,
    width_scale = width_scale,
    width_min_pixels = width_min_pixels,
    width_max_pixels = width_max_pixels,
    tooltip = eval_tooltip(rlang::enquo(tooltip), data)
  )
  add_layer(rdeck, arc_layer)
}

#' @rdname bitmap_layer
#' @autoglobal
#' @export
add_bitmap_layer <- function(rdeck,
                             ...,
                             id = "BitmapLayer",
                             data = NULL,
                             visible = TRUE,
                             pickable = FALSE,
                             opacity = 1,
                             position_format = "XYZ",
                             color_format = "RGBA",
                             auto_highlight = FALSE,
                             highlight_color = "#00008080",
                             image = NULL,
                             bounds = c(1, 0, 0, 1),
                             desaturate = 0,
                             transparent_color = "#00000000",
                             tint_color = "#ffffff",
                             tooltip = FALSE) {
  bitmap_layer <- layer(
    rdeck,
    ...,
    type = "BitmapLayer",
    data = data,
    visible = visible,
    pickable = pickable,
    opacity = opacity,
    position_format = position_format,
    color_format = color_format,
    auto_highlight = auto_highlight,
    highlight_color = accessor(rlang::enquo(highlight_color), data),
    image = image,
    bounds = bounds,
    desaturate = desaturate,
    transparent_color = transparent_color,
    tint_color = tint_color,
    tooltip = eval_tooltip(rlang::enquo(tooltip), data)
  )
  add_layer(rdeck, bitmap_layer)
}

#' @rdname icon_layer
#' @autoglobal
#' @export
add_icon_layer <- function(rdeck,
                           ...,
                           id = "IconLayer",
                           data = NULL,
                           visible = TRUE,
                           pickable = FALSE,
                           opacity = 1,
                           position_format = "XYZ",
                           color_format = "RGBA",
                           auto_highlight = FALSE,
                           highlight_color = "#00008080",
                           icon_atlas = NULL,
                           icon_mapping = NULL,
                           size_scale = 1,
                           billboard = TRUE,
                           size_units = "pixels",
                           size_min_pixels = 0,
                           size_max_pixels = 9007199254740991,
                           alpha_cutoff = 0.05,
                           get_position = position,
                           get_icon = icon,
                           get_color = "#000000ff",
                           get_size = 1,
                           get_angle = 0,
                           get_pixel_offset = c(0, 0),
                           tooltip = FALSE) {
  # auto-resolve geometry
  if (inherits(data, "sf")) {
    get_position <- as.name(attr(data, "sf_column"))
  }
  icon_layer <- layer(
    rdeck,
    ...,
    type = "IconLayer",
    data = data,
    visible = visible,
    pickable = pickable,
    opacity = opacity,
    position_format = position_format,
    color_format = color_format,
    auto_highlight = auto_highlight,
    highlight_color = accessor(rlang::enquo(highlight_color), data),
    icon_atlas = icon_atlas,
    icon_mapping = icon_mapping,
    size_scale = size_scale,
    billboard = billboard,
    size_units = size_units,
    size_min_pixels = size_min_pixels,
    size_max_pixels = size_max_pixels,
    alpha_cutoff = alpha_cutoff,
    get_position = accessor(rlang::enquo(get_position), data),
    get_icon = accessor(rlang::enquo(get_icon), data),
    get_color = accessor_scale(rlang::enquo(get_color), data),
    get_size = accessor_scale(rlang::enquo(get_size), data),
    get_angle = accessor(rlang::enquo(get_angle), data),
    get_pixel_offset = accessor(rlang::enquo(get_pixel_offset), data),
    tooltip = eval_tooltip(rlang::enquo(tooltip), data)
  )
  add_layer(rdeck, icon_layer)
}

#' @rdname line_layer
#' @autoglobal
#' @export
add_line_layer <- function(rdeck,
                           ...,
                           id = "LineLayer",
                           data = NULL,
                           visible = TRUE,
                           pickable = FALSE,
                           opacity = 1,
                           position_format = "XYZ",
                           color_format = "RGBA",
                           auto_highlight = FALSE,
                           highlight_color = "#00008080",
                           get_source_position = source_position,
                           get_target_position = target_position,
                           get_color = "#000000ff",
                           get_width = 1,
                           width_units = "pixels",
                           width_scale = 1,
                           width_min_pixels = 0,
                           width_max_pixels = 9007199254740991,
                           tooltip = FALSE) {
  line_layer <- layer(
    rdeck,
    ...,
    type = "LineLayer",
    data = data,
    visible = visible,
    pickable = pickable,
    opacity = opacity,
    position_format = position_format,
    color_format = color_format,
    auto_highlight = auto_highlight,
    highlight_color = accessor(rlang::enquo(highlight_color), data),
    get_source_position = accessor(rlang::enquo(get_source_position), data),
    get_target_position = accessor(rlang::enquo(get_target_position), data),
    get_color = accessor_scale(rlang::enquo(get_color), data),
    get_width = accessor_scale(rlang::enquo(get_width), data),
    width_units = width_units,
    width_scale = width_scale,
    width_min_pixels = width_min_pixels,
    width_max_pixels = width_max_pixels,
    tooltip = eval_tooltip(rlang::enquo(tooltip), data)
  )
  add_layer(rdeck, line_layer)
}

#' @rdname point_cloud_layer
#' @autoglobal
#' @export
add_point_cloud_layer <- function(rdeck,
                                  ...,
                                  id = "PointCloudLayer",
                                  data = NULL,
                                  visible = TRUE,
                                  pickable = FALSE,
                                  opacity = 1,
                                  position_format = "XYZ",
                                  color_format = "RGBA",
                                  auto_highlight = FALSE,
                                  highlight_color = "#00008080",
                                  size_units = "pixels",
                                  point_size = 10,
                                  get_position = position,
                                  get_normal = c(0, 0, 1),
                                  get_color = "#000000ff",
                                  material = TRUE,
                                  tooltip = FALSE) {
  # auto-resolve geometry
  if (inherits(data, "sf")) {
    get_position <- as.name(attr(data, "sf_column"))
  }
  point_cloud_layer <- layer(
    rdeck,
    ...,
    type = "PointCloudLayer",
    data = data,
    visible = visible,
    pickable = pickable,
    opacity = opacity,
    position_format = position_format,
    color_format = color_format,
    auto_highlight = auto_highlight,
    highlight_color = accessor(rlang::enquo(highlight_color), data),
    size_units = size_units,
    point_size = point_size,
    get_position = accessor(rlang::enquo(get_position), data),
    get_normal = accessor(rlang::enquo(get_normal), data),
    get_color = accessor_scale(rlang::enquo(get_color), data),
    material = material,
    tooltip = eval_tooltip(rlang::enquo(tooltip), data)
  )
  add_layer(rdeck, point_cloud_layer)
}

#' @rdname scatterplot_layer
#' @autoglobal
#' @export
add_scatterplot_layer <- function(rdeck,
                                  ...,
                                  id = "ScatterplotLayer",
                                  data = NULL,
                                  visible = TRUE,
                                  pickable = FALSE,
                                  opacity = 1,
                                  position_format = "XYZ",
                                  color_format = "RGBA",
                                  auto_highlight = FALSE,
                                  highlight_color = "#00008080",
                                  radius_units = "meters",
                                  radius_scale = 1,
                                  radius_min_pixels = 0,
                                  radius_max_pixels = 9007199254740991,
                                  line_width_units = "meters",
                                  line_width_scale = 1,
                                  line_width_min_pixels = 0,
                                  line_width_max_pixels = 9007199254740991,
                                  stroked = FALSE,
                                  filled = TRUE,
                                  get_position = position,
                                  get_radius = 1,
                                  get_fill_color = "#000000ff",
                                  get_line_color = "#000000ff",
                                  get_line_width = 1,
                                  tooltip = FALSE) {
  # auto-resolve geometry
  if (inherits(data, "sf")) {
    get_position <- as.name(attr(data, "sf_column"))
  }
  scatterplot_layer <- layer(
    rdeck,
    ...,
    type = "ScatterplotLayer",
    data = data,
    visible = visible,
    pickable = pickable,
    opacity = opacity,
    position_format = position_format,
    color_format = color_format,
    auto_highlight = auto_highlight,
    highlight_color = accessor(rlang::enquo(highlight_color), data),
    radius_units = radius_units,
    radius_scale = radius_scale,
    radius_min_pixels = radius_min_pixels,
    radius_max_pixels = radius_max_pixels,
    line_width_units = line_width_units,
    line_width_scale = line_width_scale,
    line_width_min_pixels = line_width_min_pixels,
    line_width_max_pixels = line_width_max_pixels,
    stroked = stroked,
    filled = filled,
    get_position = accessor(rlang::enquo(get_position), data),
    get_radius = accessor_scale(rlang::enquo(get_radius), data),
    get_fill_color = accessor(rlang::enquo(get_fill_color), data),
    get_line_color = accessor(rlang::enquo(get_line_color), data),
    get_line_width = accessor(rlang::enquo(get_line_width), data),
    tooltip = eval_tooltip(rlang::enquo(tooltip), data)
  )
  add_layer(rdeck, scatterplot_layer)
}

#' @rdname grid_cell_layer
#' @autoglobal
#' @export
add_grid_cell_layer <- function(rdeck,
                                ...,
                                id = "GridCellLayer",
                                data = NULL,
                                visible = TRUE,
                                pickable = FALSE,
                                opacity = 1,
                                position_format = "XYZ",
                                color_format = "RGBA",
                                auto_highlight = FALSE,
                                highlight_color = "#00008080",
                                disk_resolution = 20,
                                vertices = NULL,
                                radius = 1000,
                                angle = 0,
                                offset = c(1, 1),
                                coverage = 1,
                                elevation_scale = 1,
                                line_width_units = "meters",
                                line_width_scale = 1,
                                line_width_min_pixels = 0,
                                line_width_max_pixels = 9007199254740991,
                                extruded = TRUE,
                                wireframe = FALSE,
                                filled = TRUE,
                                stroked = FALSE,
                                get_position = position,
                                get_fill_color = "#000000ff",
                                get_line_color = "#000000ff",
                                get_line_width = 1,
                                get_elevation = 1000,
                                material = TRUE,
                                cell_size = 1000,
                                tooltip = FALSE) {
  # auto-resolve geometry
  if (inherits(data, "sf")) {
    get_position <- as.name(attr(data, "sf_column"))
  }
  grid_cell_layer <- layer(
    rdeck,
    ...,
    type = "GridCellLayer",
    data = data,
    visible = visible,
    pickable = pickable,
    opacity = opacity,
    position_format = position_format,
    color_format = color_format,
    auto_highlight = auto_highlight,
    highlight_color = accessor(rlang::enquo(highlight_color), data),
    disk_resolution = disk_resolution,
    vertices = vertices,
    radius = radius,
    angle = angle,
    offset = offset,
    coverage = coverage,
    elevation_scale = elevation_scale,
    line_width_units = line_width_units,
    line_width_scale = line_width_scale,
    line_width_min_pixels = line_width_min_pixels,
    line_width_max_pixels = line_width_max_pixels,
    extruded = extruded,
    wireframe = wireframe,
    filled = filled,
    stroked = stroked,
    get_position = accessor(rlang::enquo(get_position), data),
    get_fill_color = accessor(rlang::enquo(get_fill_color), data),
    get_line_color = accessor(rlang::enquo(get_line_color), data),
    get_line_width = accessor(rlang::enquo(get_line_width), data),
    get_elevation = accessor_scale(rlang::enquo(get_elevation), data),
    material = material,
    cell_size = cell_size,
    tooltip = eval_tooltip(rlang::enquo(tooltip), data)
  )
  add_layer(rdeck, grid_cell_layer)
}

#' @rdname column_layer
#' @autoglobal
#' @export
add_column_layer <- function(rdeck,
                             ...,
                             id = "ColumnLayer",
                             data = NULL,
                             visible = TRUE,
                             pickable = FALSE,
                             opacity = 1,
                             position_format = "XYZ",
                             color_format = "RGBA",
                             auto_highlight = FALSE,
                             highlight_color = "#00008080",
                             disk_resolution = 20,
                             vertices = NULL,
                             radius = 1000,
                             angle = 0,
                             offset = c(0, 0),
                             coverage = 1,
                             elevation_scale = 1,
                             line_width_units = "meters",
                             line_width_scale = 1,
                             line_width_min_pixels = 0,
                             line_width_max_pixels = 9007199254740991,
                             extruded = TRUE,
                             wireframe = FALSE,
                             filled = TRUE,
                             stroked = FALSE,
                             get_position = position,
                             get_fill_color = "#000000ff",
                             get_line_color = "#000000ff",
                             get_line_width = 1,
                             get_elevation = 1000,
                             material = TRUE,
                             tooltip = FALSE) {
  # auto-resolve geometry
  if (inherits(data, "sf")) {
    get_position <- as.name(attr(data, "sf_column"))
  }
  column_layer <- layer(
    rdeck,
    ...,
    type = "ColumnLayer",
    data = data,
    visible = visible,
    pickable = pickable,
    opacity = opacity,
    position_format = position_format,
    color_format = color_format,
    auto_highlight = auto_highlight,
    highlight_color = accessor(rlang::enquo(highlight_color), data),
    disk_resolution = disk_resolution,
    vertices = vertices,
    radius = radius,
    angle = angle,
    offset = offset,
    coverage = coverage,
    elevation_scale = elevation_scale,
    line_width_units = line_width_units,
    line_width_scale = line_width_scale,
    line_width_min_pixels = line_width_min_pixels,
    line_width_max_pixels = line_width_max_pixels,
    extruded = extruded,
    wireframe = wireframe,
    filled = filled,
    stroked = stroked,
    get_position = accessor(rlang::enquo(get_position), data),
    get_fill_color = accessor(rlang::enquo(get_fill_color), data),
    get_line_color = accessor(rlang::enquo(get_line_color), data),
    get_line_width = accessor(rlang::enquo(get_line_width), data),
    get_elevation = accessor_scale(rlang::enquo(get_elevation), data),
    material = material,
    tooltip = eval_tooltip(rlang::enquo(tooltip), data)
  )
  add_layer(rdeck, column_layer)
}

#' @rdname path_layer
#' @autoglobal
#' @export
add_path_layer <- function(rdeck,
                           ...,
                           id = "PathLayer",
                           data = NULL,
                           visible = TRUE,
                           pickable = FALSE,
                           opacity = 1,
                           position_format = "XYZ",
                           color_format = "RGBA",
                           auto_highlight = FALSE,
                           highlight_color = "#00008080",
                           width_units = "meters",
                           width_scale = 1,
                           width_min_pixels = 0,
                           width_max_pixels = 9007199254740991,
                           rounded = FALSE,
                           miter_limit = 4,
                           billboard = FALSE,
                           get_path = path,
                           get_color = "#000000ff",
                           get_width = 1,
                           tooltip = FALSE) {
  # auto-resolve geometry
  if (inherits(data, "sf")) {
    get_path <- as.name(attr(data, "sf_column"))
  }
  path_layer <- layer(
    rdeck,
    ...,
    type = "PathLayer",
    data = data,
    visible = visible,
    pickable = pickable,
    opacity = opacity,
    position_format = position_format,
    color_format = color_format,
    auto_highlight = auto_highlight,
    highlight_color = accessor(rlang::enquo(highlight_color), data),
    width_units = width_units,
    width_scale = width_scale,
    width_min_pixels = width_min_pixels,
    width_max_pixels = width_max_pixels,
    rounded = rounded,
    miter_limit = miter_limit,
    billboard = billboard,
    get_path = accessor(rlang::enquo(get_path), data),
    get_color = accessor_scale(rlang::enquo(get_color), data),
    get_width = accessor_scale(rlang::enquo(get_width), data),
    tooltip = eval_tooltip(rlang::enquo(tooltip), data)
  )
  add_layer(rdeck, path_layer)
}

#' @rdname polygon_layer
#' @autoglobal
#' @export
add_polygon_layer <- function(rdeck,
                              ...,
                              id = "PolygonLayer",
                              data = NULL,
                              visible = TRUE,
                              pickable = FALSE,
                              opacity = 1,
                              position_format = "XYZ",
                              color_format = "RGBA",
                              auto_highlight = FALSE,
                              highlight_color = "#00008080",
                              stroked = TRUE,
                              filled = TRUE,
                              extruded = FALSE,
                              elevation_scale = 1,
                              wireframe = FALSE,
                              line_width_units = "meters",
                              line_width_scale = 1,
                              line_width_min_pixels = 0,
                              line_width_max_pixels = 9007199254740991,
                              line_joint_rounded = FALSE,
                              line_miter_limit = 4,
                              get_polygon = polygon,
                              get_fill_color = "#000000ff",
                              get_line_color = "#000000ff",
                              get_line_width = 1,
                              get_elevation = 1000,
                              material = TRUE,
                              tooltip = FALSE) {
  # auto-resolve geometry
  if (inherits(data, "sf")) {
    get_polygon <- as.name(attr(data, "sf_column"))
  }
  polygon_layer <- layer(
    rdeck,
    ...,
    type = "PolygonLayer",
    data = data,
    visible = visible,
    pickable = pickable,
    opacity = opacity,
    position_format = position_format,
    color_format = color_format,
    auto_highlight = auto_highlight,
    highlight_color = accessor(rlang::enquo(highlight_color), data),
    stroked = stroked,
    filled = filled,
    extruded = extruded,
    elevation_scale = elevation_scale,
    wireframe = wireframe,
    line_width_units = line_width_units,
    line_width_scale = line_width_scale,
    line_width_min_pixels = line_width_min_pixels,
    line_width_max_pixels = line_width_max_pixels,
    line_joint_rounded = line_joint_rounded,
    line_miter_limit = line_miter_limit,
    get_polygon = accessor(rlang::enquo(get_polygon), data),
    get_fill_color = accessor(rlang::enquo(get_fill_color), data),
    get_line_color = accessor(rlang::enquo(get_line_color), data),
    get_line_width = accessor(rlang::enquo(get_line_width), data),
    get_elevation = accessor_scale(rlang::enquo(get_elevation), data),
    material = material,
    tooltip = eval_tooltip(rlang::enquo(tooltip), data)
  )
  add_layer(rdeck, polygon_layer)
}

#' @rdname solid_polygon_layer
#' @autoglobal
#' @export
add_solid_polygon_layer <- function(rdeck,
                                    ...,
                                    id = "SolidPolygonLayer",
                                    data = NULL,
                                    visible = TRUE,
                                    pickable = FALSE,
                                    opacity = 1,
                                    position_format = "XYZ",
                                    color_format = "RGBA",
                                    auto_highlight = FALSE,
                                    highlight_color = "#00008080",
                                    filled = TRUE,
                                    extruded = FALSE,
                                    wireframe = FALSE,
                                    elevation_scale = 1,
                                    get_polygon = polygon,
                                    get_elevation = 1000,
                                    get_fill_color = "#000000ff",
                                    get_line_color = "#000000ff",
                                    material = TRUE,
                                    tooltip = FALSE) {
  # auto-resolve geometry
  if (inherits(data, "sf")) {
    get_polygon <- as.name(attr(data, "sf_column"))
  }
  solid_polygon_layer <- layer(
    rdeck,
    ...,
    type = "SolidPolygonLayer",
    data = data,
    visible = visible,
    pickable = pickable,
    opacity = opacity,
    position_format = position_format,
    color_format = color_format,
    auto_highlight = auto_highlight,
    highlight_color = accessor(rlang::enquo(highlight_color), data),
    filled = filled,
    extruded = extruded,
    wireframe = wireframe,
    elevation_scale = elevation_scale,
    get_polygon = accessor(rlang::enquo(get_polygon), data),
    get_elevation = accessor_scale(rlang::enquo(get_elevation), data),
    get_fill_color = accessor(rlang::enquo(get_fill_color), data),
    get_line_color = accessor(rlang::enquo(get_line_color), data),
    material = material,
    tooltip = eval_tooltip(rlang::enquo(tooltip), data)
  )
  add_layer(rdeck, solid_polygon_layer)
}

#' @rdname geojson_layer
#' @autoglobal
#' @export
add_geojson_layer <- function(rdeck,
                              ...,
                              id = "GeoJsonLayer",
                              data = NULL,
                              visible = TRUE,
                              pickable = FALSE,
                              opacity = 1,
                              position_format = "XYZ",
                              color_format = "RGBA",
                              auto_highlight = FALSE,
                              highlight_color = "#00008080",
                              stroked = TRUE,
                              filled = TRUE,
                              extruded = FALSE,
                              wireframe = FALSE,
                              line_width_units = "meters",
                              line_width_scale = 1,
                              line_width_min_pixels = 0,
                              line_width_max_pixels = 9007199254740991,
                              line_joint_rounded = FALSE,
                              line_miter_limit = 4,
                              elevation_scale = 1,
                              point_radius_units = "meters",
                              point_radius_scale = 1,
                              point_radius_min_pixels = 0,
                              point_radius_max_pixels = 9007199254740991,
                              get_line_color = "#000000ff",
                              get_fill_color = "#000000ff",
                              get_radius = 1,
                              get_line_width = 1,
                              get_elevation = 1000,
                              material = TRUE,
                              tooltip = FALSE) {
  geojson_layer <- layer(
    rdeck,
    ...,
    type = "GeoJsonLayer",
    data = data,
    visible = visible,
    pickable = pickable,
    opacity = opacity,
    position_format = position_format,
    color_format = color_format,
    auto_highlight = auto_highlight,
    highlight_color = accessor(rlang::enquo(highlight_color), data),
    stroked = stroked,
    filled = filled,
    extruded = extruded,
    wireframe = wireframe,
    line_width_units = line_width_units,
    line_width_scale = line_width_scale,
    line_width_min_pixels = line_width_min_pixels,
    line_width_max_pixels = line_width_max_pixels,
    line_joint_rounded = line_joint_rounded,
    line_miter_limit = line_miter_limit,
    elevation_scale = elevation_scale,
    point_radius_units = point_radius_units,
    point_radius_scale = point_radius_scale,
    point_radius_min_pixels = point_radius_min_pixels,
    point_radius_max_pixels = point_radius_max_pixels,
    get_line_color = accessor(rlang::enquo(get_line_color), data),
    get_fill_color = accessor(rlang::enquo(get_fill_color), data),
    get_radius = accessor_scale(rlang::enquo(get_radius), data),
    get_line_width = accessor(rlang::enquo(get_line_width), data),
    get_elevation = accessor_scale(rlang::enquo(get_elevation), data),
    material = material,
    tooltip = eval_tooltip(rlang::enquo(tooltip), data)
  )
  add_layer(rdeck, geojson_layer)
}

#' @rdname text_layer
#' @autoglobal
#' @export
add_text_layer <- function(rdeck,
                           ...,
                           id = "TextLayer",
                           data = NULL,
                           visible = TRUE,
                           pickable = FALSE,
                           opacity = 1,
                           position_format = "XYZ",
                           color_format = "RGBA",
                           auto_highlight = FALSE,
                           highlight_color = "#00008080",
                           billboard = TRUE,
                           size_scale = 1,
                           size_units = "pixels",
                           size_min_pixels = 0,
                           size_max_pixels = 9007199254740991,
                           background_color = NULL,
                           font_family = "Roboto, san-serif",
                           font_weight = "normal",
                           line_height = 1,
                           font_settings = list(sdf = TRUE),
                           word_break = "word-break",
                           max_width = -1,
                           get_text = text,
                           get_position = position,
                           get_color = "#000000ff",
                           get_size = 32,
                           get_angle = 0,
                           get_text_anchor = "middle",
                           get_alignment_baseline = "center",
                           get_pixel_offset = c(0, 0),
                           tooltip = FALSE) {
  # auto-resolve geometry
  if (inherits(data, "sf")) {
    get_position <- as.name(attr(data, "sf_column"))
  }
  text_layer <- layer(
    rdeck,
    ...,
    type = "TextLayer",
    data = data,
    visible = visible,
    pickable = pickable,
    opacity = opacity,
    position_format = position_format,
    color_format = color_format,
    auto_highlight = auto_highlight,
    highlight_color = accessor(rlang::enquo(highlight_color), data),
    billboard = billboard,
    size_scale = size_scale,
    size_units = size_units,
    size_min_pixels = size_min_pixels,
    size_max_pixels = size_max_pixels,
    background_color = background_color,
    font_family = font_family,
    font_weight = font_weight,
    line_height = line_height,
    font_settings = font_settings,
    word_break = word_break,
    max_width = max_width,
    get_text = accessor(rlang::enquo(get_text), data),
    get_position = accessor(rlang::enquo(get_position), data),
    get_color = accessor_scale(rlang::enquo(get_color), data),
    get_size = accessor_scale(rlang::enquo(get_size), data),
    get_angle = accessor(rlang::enquo(get_angle), data),
    get_text_anchor = accessor(rlang::enquo(get_text_anchor), data),
    get_alignment_baseline = accessor(rlang::enquo(get_alignment_baseline), data),
    get_pixel_offset = accessor(rlang::enquo(get_pixel_offset), data),
    tooltip = eval_tooltip(rlang::enquo(tooltip), data)
  )
  add_layer(rdeck, text_layer)
}

#' @rdname screen_grid_layer
#' @autoglobal
#' @export
add_screen_grid_layer <- function(rdeck,
                                  ...,
                                  id = "ScreenGridLayer",
                                  data = NULL,
                                  visible = TRUE,
                                  pickable = FALSE,
                                  opacity = 1,
                                  position_format = "XYZ",
                                  color_format = "RGBA",
                                  auto_highlight = FALSE,
                                  highlight_color = "#00008080",
                                  cell_size_pixels = 100,
                                  cell_margin_pixels = 2,
                                  color_domain = NULL,
                                  color_range = c("#ffffb2", "#fed976", "#feb24c", "#fd8d3c", "#f03b20", "#bd0026"),
                                  get_position = position,
                                  get_weight = 1,
                                  gpu_aggregation = TRUE,
                                  aggregation = "SUM",
                                  tooltip = FALSE) {
  # auto-resolve geometry
  if (inherits(data, "sf")) {
    get_position <- as.name(attr(data, "sf_column"))
  }
  screen_grid_layer <- layer(
    rdeck,
    ...,
    type = "ScreenGridLayer",
    data = data,
    visible = visible,
    pickable = pickable,
    opacity = opacity,
    position_format = position_format,
    color_format = color_format,
    auto_highlight = auto_highlight,
    highlight_color = accessor(rlang::enquo(highlight_color), data),
    cell_size_pixels = cell_size_pixels,
    cell_margin_pixels = cell_margin_pixels,
    color_domain = color_domain,
    color_range = color_range,
    get_position = accessor(rlang::enquo(get_position), data),
    get_weight = accessor_scale(rlang::enquo(get_weight), data),
    gpu_aggregation = gpu_aggregation,
    aggregation = aggregation,
    tooltip = eval_tooltip(rlang::enquo(tooltip), data)
  )
  add_layer(rdeck, screen_grid_layer)
}

#' @rdname cpu_grid_layer
#' @autoglobal
#' @export
add_cpu_grid_layer <- function(rdeck,
                               ...,
                               id = "CPUGridLayer",
                               data = NULL,
                               visible = TRUE,
                               pickable = FALSE,
                               opacity = 1,
                               position_format = "XYZ",
                               color_format = "RGBA",
                               auto_highlight = FALSE,
                               highlight_color = "#00008080",
                               color_domain = NULL,
                               color_range = c("#ffffb2", "#fed976", "#feb24c", "#fd8d3c", "#f03b20", "#bd0026"),
                               get_color_value = NULL,
                               get_color_weight = 1,
                               color_aggregation = "SUM",
                               lower_percentile = 0,
                               upper_percentile = 100,
                               color_scale_type = "quantize",
                               elevation_domain = NULL,
                               elevation_range = c(0, 1000),
                               get_elevation_value = NULL,
                               get_elevation_weight = 1,
                               elevation_aggregation = "SUM",
                               elevation_lower_percentile = 0,
                               elevation_upper_percentile = 100,
                               elevation_scale = 1,
                               elevation_scale_type = "linear",
                               grid_aggregator = NULL,
                               cell_size = 1000,
                               coverage = 1,
                               get_position = position,
                               extruded = FALSE,
                               material = TRUE,
                               tooltip = FALSE) {
  # auto-resolve geometry
  if (inherits(data, "sf")) {
    get_position <- as.name(attr(data, "sf_column"))
  }
  cpu_grid_layer <- layer(
    rdeck,
    ...,
    type = "CPUGridLayer",
    data = data,
    visible = visible,
    pickable = pickable,
    opacity = opacity,
    position_format = position_format,
    color_format = color_format,
    auto_highlight = auto_highlight,
    highlight_color = accessor(rlang::enquo(highlight_color), data),
    color_domain = color_domain,
    color_range = color_range,
    get_color_value = accessor(rlang::enquo(get_color_value), data),
    get_color_weight = accessor(rlang::enquo(get_color_weight), data),
    color_aggregation = color_aggregation,
    lower_percentile = lower_percentile,
    upper_percentile = upper_percentile,
    color_scale_type = color_scale_type,
    elevation_domain = elevation_domain,
    elevation_range = elevation_range,
    get_elevation_value = accessor(rlang::enquo(get_elevation_value), data),
    get_elevation_weight = accessor(rlang::enquo(get_elevation_weight), data),
    elevation_aggregation = elevation_aggregation,
    elevation_lower_percentile = elevation_lower_percentile,
    elevation_upper_percentile = elevation_upper_percentile,
    elevation_scale = elevation_scale,
    elevation_scale_type = elevation_scale_type,
    grid_aggregator = grid_aggregator,
    cell_size = cell_size,
    coverage = coverage,
    get_position = accessor(rlang::enquo(get_position), data),
    extruded = extruded,
    material = material,
    tooltip = eval_tooltip(rlang::enquo(tooltip), data)
  )
  add_layer(rdeck, cpu_grid_layer)
}

#' @rdname hexagon_layer
#' @autoglobal
#' @export
add_hexagon_layer <- function(rdeck,
                              ...,
                              id = "HexagonLayer",
                              data = NULL,
                              visible = TRUE,
                              pickable = FALSE,
                              opacity = 1,
                              position_format = "XYZ",
                              color_format = "RGBA",
                              auto_highlight = FALSE,
                              highlight_color = "#00008080",
                              color_domain = NULL,
                              color_range = c("#ffffb2", "#fed976", "#feb24c", "#fd8d3c", "#f03b20", "#bd0026"),
                              get_color_value = NULL,
                              get_color_weight = 1,
                              color_aggregation = "SUM",
                              lower_percentile = 0,
                              upper_percentile = 100,
                              color_scale_type = "quantize",
                              elevation_domain = NULL,
                              elevation_range = c(0, 1000),
                              get_elevation_value = NULL,
                              get_elevation_weight = 1,
                              elevation_aggregation = "SUM",
                              elevation_lower_percentile = 0,
                              elevation_upper_percentile = 100,
                              elevation_scale = 1,
                              elevation_scale_type = "linear",
                              radius = 1000,
                              coverage = 1,
                              extruded = FALSE,
                              hexagon_aggregator = NULL,
                              get_position = position,
                              material = TRUE,
                              tooltip = FALSE) {
  # auto-resolve geometry
  if (inherits(data, "sf")) {
    get_position <- as.name(attr(data, "sf_column"))
  }
  hexagon_layer <- layer(
    rdeck,
    ...,
    type = "HexagonLayer",
    data = data,
    visible = visible,
    pickable = pickable,
    opacity = opacity,
    position_format = position_format,
    color_format = color_format,
    auto_highlight = auto_highlight,
    highlight_color = accessor(rlang::enquo(highlight_color), data),
    color_domain = color_domain,
    color_range = color_range,
    get_color_value = accessor(rlang::enquo(get_color_value), data),
    get_color_weight = accessor(rlang::enquo(get_color_weight), data),
    color_aggregation = color_aggregation,
    lower_percentile = lower_percentile,
    upper_percentile = upper_percentile,
    color_scale_type = color_scale_type,
    elevation_domain = elevation_domain,
    elevation_range = elevation_range,
    get_elevation_value = accessor(rlang::enquo(get_elevation_value), data),
    get_elevation_weight = accessor(rlang::enquo(get_elevation_weight), data),
    elevation_aggregation = elevation_aggregation,
    elevation_lower_percentile = elevation_lower_percentile,
    elevation_upper_percentile = elevation_upper_percentile,
    elevation_scale = elevation_scale,
    elevation_scale_type = elevation_scale_type,
    radius = radius,
    coverage = coverage,
    extruded = extruded,
    hexagon_aggregator = hexagon_aggregator,
    get_position = accessor(rlang::enquo(get_position), data),
    material = material,
    tooltip = eval_tooltip(rlang::enquo(tooltip), data)
  )
  add_layer(rdeck, hexagon_layer)
}

#' @rdname contour_layer
#' @autoglobal
#' @export
add_contour_layer <- function(rdeck,
                              ...,
                              id = "ContourLayer",
                              data = NULL,
                              visible = TRUE,
                              pickable = FALSE,
                              opacity = 1,
                              position_format = "XYZ",
                              color_format = "RGBA",
                              auto_highlight = FALSE,
                              highlight_color = "#00008080",
                              cell_size = 1000,
                              get_position = position,
                              get_weight = 1,
                              gpu_aggregation = TRUE,
                              aggregation = "SUM",
                              contours = c(list(threshold = 1)),
                              z_offset = 0.005,
                              tooltip = FALSE) {
  # auto-resolve geometry
  if (inherits(data, "sf")) {
    get_position <- as.name(attr(data, "sf_column"))
  }
  contour_layer <- layer(
    rdeck,
    ...,
    type = "ContourLayer",
    data = data,
    visible = visible,
    pickable = pickable,
    opacity = opacity,
    position_format = position_format,
    color_format = color_format,
    auto_highlight = auto_highlight,
    highlight_color = accessor(rlang::enquo(highlight_color), data),
    cell_size = cell_size,
    get_position = accessor(rlang::enquo(get_position), data),
    get_weight = accessor_scale(rlang::enquo(get_weight), data),
    gpu_aggregation = gpu_aggregation,
    aggregation = aggregation,
    contours = contours,
    z_offset = z_offset,
    tooltip = eval_tooltip(rlang::enquo(tooltip), data)
  )
  add_layer(rdeck, contour_layer)
}

#' @rdname grid_layer
#' @autoglobal
#' @export
add_grid_layer <- function(rdeck,
                           ...,
                           id = "GridLayer",
                           data = NULL,
                           visible = TRUE,
                           pickable = FALSE,
                           opacity = 1,
                           position_format = "XYZ",
                           color_format = "RGBA",
                           auto_highlight = FALSE,
                           highlight_color = "#00008080",
                           color_domain = NULL,
                           color_range = c("#ffffb2", "#fed976", "#feb24c", "#fd8d3c", "#f03b20", "#bd0026"),
                           get_color_weight = 1,
                           color_aggregation = "SUM",
                           elevation_domain = NULL,
                           elevation_range = c(0, 1000),
                           get_elevation_weight = 1,
                           elevation_aggregation = "SUM",
                           elevation_scale = 1,
                           cell_size = 1000,
                           coverage = 1,
                           get_position = position,
                           extruded = FALSE,
                           material = TRUE,
                           get_color_value = NULL,
                           lower_percentile = 0,
                           upper_percentile = 100,
                           color_scale_type = "quantize",
                           get_elevation_value = NULL,
                           elevation_lower_percentile = 0,
                           elevation_upper_percentile = 100,
                           elevation_scale_type = "linear",
                           grid_aggregator = NULL,
                           gpu_aggregation = FALSE,
                           tooltip = FALSE) {
  # auto-resolve geometry
  if (inherits(data, "sf")) {
    get_position <- as.name(attr(data, "sf_column"))
  }
  grid_layer <- layer(
    rdeck,
    ...,
    type = "GridLayer",
    data = data,
    visible = visible,
    pickable = pickable,
    opacity = opacity,
    position_format = position_format,
    color_format = color_format,
    auto_highlight = auto_highlight,
    highlight_color = accessor(rlang::enquo(highlight_color), data),
    color_domain = color_domain,
    color_range = color_range,
    get_color_weight = accessor(rlang::enquo(get_color_weight), data),
    color_aggregation = color_aggregation,
    elevation_domain = elevation_domain,
    elevation_range = elevation_range,
    get_elevation_weight = accessor(rlang::enquo(get_elevation_weight), data),
    elevation_aggregation = elevation_aggregation,
    elevation_scale = elevation_scale,
    cell_size = cell_size,
    coverage = coverage,
    get_position = accessor(rlang::enquo(get_position), data),
    extruded = extruded,
    material = material,
    get_color_value = accessor(rlang::enquo(get_color_value), data),
    lower_percentile = lower_percentile,
    upper_percentile = upper_percentile,
    color_scale_type = color_scale_type,
    get_elevation_value = accessor(rlang::enquo(get_elevation_value), data),
    elevation_lower_percentile = elevation_lower_percentile,
    elevation_upper_percentile = elevation_upper_percentile,
    elevation_scale_type = elevation_scale_type,
    grid_aggregator = grid_aggregator,
    gpu_aggregation = gpu_aggregation,
    tooltip = eval_tooltip(rlang::enquo(tooltip), data)
  )
  add_layer(rdeck, grid_layer)
}

#' @rdname gpu_grid_layer
#' @autoglobal
#' @export
add_gpu_grid_layer <- function(rdeck,
                               ...,
                               id = "GPUGridLayer",
                               data = NULL,
                               visible = TRUE,
                               pickable = FALSE,
                               opacity = 1,
                               position_format = "XYZ",
                               color_format = "RGBA",
                               auto_highlight = FALSE,
                               highlight_color = "#00008080",
                               color_domain = NULL,
                               color_range = c("#ffffb2", "#fed976", "#feb24c", "#fd8d3c", "#f03b20", "#bd0026"),
                               get_color_weight = 1,
                               color_aggregation = "SUM",
                               elevation_domain = NULL,
                               elevation_range = c(0, 1000),
                               get_elevation_weight = 1,
                               elevation_aggregation = "SUM",
                               elevation_scale = 1,
                               cell_size = 1000,
                               coverage = 1,
                               get_position = position,
                               extruded = FALSE,
                               material = TRUE,
                               tooltip = FALSE) {
  # auto-resolve geometry
  if (inherits(data, "sf")) {
    get_position <- as.name(attr(data, "sf_column"))
  }
  gpu_grid_layer <- layer(
    rdeck,
    ...,
    type = "GPUGridLayer",
    data = data,
    visible = visible,
    pickable = pickable,
    opacity = opacity,
    position_format = position_format,
    color_format = color_format,
    auto_highlight = auto_highlight,
    highlight_color = accessor(rlang::enquo(highlight_color), data),
    color_domain = color_domain,
    color_range = color_range,
    get_color_weight = accessor(rlang::enquo(get_color_weight), data),
    color_aggregation = color_aggregation,
    elevation_domain = elevation_domain,
    elevation_range = elevation_range,
    get_elevation_weight = accessor(rlang::enquo(get_elevation_weight), data),
    elevation_aggregation = elevation_aggregation,
    elevation_scale = elevation_scale,
    cell_size = cell_size,
    coverage = coverage,
    get_position = accessor(rlang::enquo(get_position), data),
    extruded = extruded,
    material = material,
    tooltip = eval_tooltip(rlang::enquo(tooltip), data)
  )
  add_layer(rdeck, gpu_grid_layer)
}

#' @rdname heatmap_layer
#' @autoglobal
#' @export
add_heatmap_layer <- function(rdeck,
                              ...,
                              id = "HeatmapLayer",
                              data = NULL,
                              visible = TRUE,
                              pickable = FALSE,
                              opacity = 1,
                              position_format = "XYZ",
                              color_format = "RGBA",
                              auto_highlight = FALSE,
                              highlight_color = "#00008080",
                              get_position = position,
                              get_weight = 1,
                              intensity = 1,
                              radius_pixels = 50,
                              color_range = c("#ffffb2", "#fed976", "#feb24c", "#fd8d3c", "#f03b20", "#bd0026"),
                              threshold = 0.05,
                              color_domain = NULL,
                              tooltip = FALSE) {
  # auto-resolve geometry
  if (inherits(data, "sf")) {
    get_position <- as.name(attr(data, "sf_column"))
  }
  heatmap_layer <- layer(
    rdeck,
    ...,
    type = "HeatmapLayer",
    data = data,
    visible = visible,
    pickable = pickable,
    opacity = opacity,
    position_format = position_format,
    color_format = color_format,
    auto_highlight = auto_highlight,
    highlight_color = accessor(rlang::enquo(highlight_color), data),
    get_position = accessor(rlang::enquo(get_position), data),
    get_weight = accessor_scale(rlang::enquo(get_weight), data),
    intensity = intensity,
    radius_pixels = radius_pixels,
    color_range = color_range,
    threshold = threshold,
    color_domain = color_domain,
    tooltip = eval_tooltip(rlang::enquo(tooltip), data)
  )
  add_layer(rdeck, heatmap_layer)
}

#' @rdname great_circle_layer
#' @autoglobal
#' @export
add_great_circle_layer <- function(rdeck,
                                   ...,
                                   id = "GreatCircleLayer",
                                   data = NULL,
                                   visible = TRUE,
                                   pickable = FALSE,
                                   opacity = 1,
                                   position_format = "XYZ",
                                   color_format = "RGBA",
                                   auto_highlight = FALSE,
                                   highlight_color = "#00008080",
                                   get_source_position = source_position,
                                   get_target_position = target_position,
                                   get_source_color = "#000000ff",
                                   get_target_color = "#000000ff",
                                   get_width = 1,
                                   get_height = 0,
                                   get_tilt = 0,
                                   great_circle = TRUE,
                                   width_units = "pixels",
                                   width_scale = 1,
                                   width_min_pixels = 0,
                                   width_max_pixels = 9007199254740991,
                                   tooltip = FALSE) {
  great_circle_layer <- layer(
    rdeck,
    ...,
    type = "GreatCircleLayer",
    data = data,
    visible = visible,
    pickable = pickable,
    opacity = opacity,
    position_format = position_format,
    color_format = color_format,
    auto_highlight = auto_highlight,
    highlight_color = accessor(rlang::enquo(highlight_color), data),
    get_source_position = accessor(rlang::enquo(get_source_position), data),
    get_target_position = accessor(rlang::enquo(get_target_position), data),
    get_source_color = accessor(rlang::enquo(get_source_color), data),
    get_target_color = accessor(rlang::enquo(get_target_color), data),
    get_width = accessor_scale(rlang::enquo(get_width), data),
    get_height = accessor_scale(rlang::enquo(get_height), data),
    get_tilt = accessor(rlang::enquo(get_tilt), data),
    great_circle = great_circle,
    width_units = width_units,
    width_scale = width_scale,
    width_min_pixels = width_min_pixels,
    width_max_pixels = width_max_pixels,
    tooltip = eval_tooltip(rlang::enquo(tooltip), data)
  )
  add_layer(rdeck, great_circle_layer)
}

#' @rdname s2_layer
#' @autoglobal
#' @export
add_s2_layer <- function(rdeck,
                         ...,
                         id = "S2Layer",
                         data = NULL,
                         visible = TRUE,
                         pickable = FALSE,
                         opacity = 1,
                         position_format = "XYZ",
                         color_format = "RGBA",
                         auto_highlight = FALSE,
                         highlight_color = "#00008080",
                         get_s2_token = token,
                         stroked = TRUE,
                         filled = TRUE,
                         extruded = FALSE,
                         elevation_scale = 1,
                         wireframe = FALSE,
                         line_width_units = "meters",
                         line_width_scale = 1,
                         line_width_min_pixels = 0,
                         line_width_max_pixels = 9007199254740991,
                         line_joint_rounded = FALSE,
                         line_miter_limit = 4,
                         get_fill_color = "#000000ff",
                         get_line_color = "#000000ff",
                         get_line_width = 1,
                         get_elevation = 1000,
                         material = TRUE,
                         tooltip = FALSE) {
  s2_layer <- layer(
    rdeck,
    ...,
    type = "S2Layer",
    data = data,
    visible = visible,
    pickable = pickable,
    opacity = opacity,
    position_format = position_format,
    color_format = color_format,
    auto_highlight = auto_highlight,
    highlight_color = accessor(rlang::enquo(highlight_color), data),
    get_s2_token = accessor(rlang::enquo(get_s2_token), data),
    stroked = stroked,
    filled = filled,
    extruded = extruded,
    elevation_scale = elevation_scale,
    wireframe = wireframe,
    line_width_units = line_width_units,
    line_width_scale = line_width_scale,
    line_width_min_pixels = line_width_min_pixels,
    line_width_max_pixels = line_width_max_pixels,
    line_joint_rounded = line_joint_rounded,
    line_miter_limit = line_miter_limit,
    get_fill_color = accessor(rlang::enquo(get_fill_color), data),
    get_line_color = accessor(rlang::enquo(get_line_color), data),
    get_line_width = accessor(rlang::enquo(get_line_width), data),
    get_elevation = accessor_scale(rlang::enquo(get_elevation), data),
    material = material,
    tooltip = eval_tooltip(rlang::enquo(tooltip), data)
  )
  add_layer(rdeck, s2_layer)
}

#' @rdname h3_cluster_layer
#' @autoglobal
#' @export
add_h3_cluster_layer <- function(rdeck,
                                 ...,
                                 id = "H3ClusterLayer",
                                 data = NULL,
                                 visible = TRUE,
                                 pickable = FALSE,
                                 opacity = 1,
                                 position_format = "XYZ",
                                 color_format = "RGBA",
                                 auto_highlight = FALSE,
                                 highlight_color = "#00008080",
                                 get_hexagons = hexagons,
                                 stroked = TRUE,
                                 filled = TRUE,
                                 extruded = FALSE,
                                 elevation_scale = 1,
                                 wireframe = FALSE,
                                 line_width_units = "meters",
                                 line_width_scale = 1,
                                 line_width_min_pixels = 0,
                                 line_width_max_pixels = 9007199254740991,
                                 line_joint_rounded = FALSE,
                                 line_miter_limit = 4,
                                 get_fill_color = "#000000ff",
                                 get_line_color = "#000000ff",
                                 get_line_width = 1,
                                 get_elevation = 1000,
                                 material = TRUE,
                                 tooltip = FALSE) {
  h3_cluster_layer <- layer(
    rdeck,
    ...,
    type = "H3ClusterLayer",
    data = data,
    visible = visible,
    pickable = pickable,
    opacity = opacity,
    position_format = position_format,
    color_format = color_format,
    auto_highlight = auto_highlight,
    highlight_color = accessor(rlang::enquo(highlight_color), data),
    get_hexagons = accessor(rlang::enquo(get_hexagons), data),
    stroked = stroked,
    filled = filled,
    extruded = extruded,
    elevation_scale = elevation_scale,
    wireframe = wireframe,
    line_width_units = line_width_units,
    line_width_scale = line_width_scale,
    line_width_min_pixels = line_width_min_pixels,
    line_width_max_pixels = line_width_max_pixels,
    line_joint_rounded = line_joint_rounded,
    line_miter_limit = line_miter_limit,
    get_fill_color = accessor(rlang::enquo(get_fill_color), data),
    get_line_color = accessor(rlang::enquo(get_line_color), data),
    get_line_width = accessor(rlang::enquo(get_line_width), data),
    get_elevation = accessor_scale(rlang::enquo(get_elevation), data),
    material = material,
    tooltip = eval_tooltip(rlang::enquo(tooltip), data)
  )
  add_layer(rdeck, h3_cluster_layer)
}

#' @rdname h3_hexagon_layer
#' @autoglobal
#' @export
add_h3_hexagon_layer <- function(rdeck,
                                 ...,
                                 id = "H3HexagonLayer",
                                 data = NULL,
                                 visible = TRUE,
                                 pickable = FALSE,
                                 opacity = 1,
                                 position_format = "XYZ",
                                 color_format = "RGBA",
                                 auto_highlight = FALSE,
                                 highlight_color = "#00008080",
                                 stroked = TRUE,
                                 filled = TRUE,
                                 extruded = TRUE,
                                 elevation_scale = 1,
                                 wireframe = FALSE,
                                 line_width_units = "meters",
                                 line_width_scale = 1,
                                 line_width_min_pixels = 0,
                                 line_width_max_pixels = 9007199254740991,
                                 line_joint_rounded = FALSE,
                                 line_miter_limit = 4,
                                 get_fill_color = "#000000ff",
                                 get_line_color = "#000000ff",
                                 get_line_width = 1,
                                 get_elevation = 1000,
                                 material = TRUE,
                                 high_precision = FALSE,
                                 coverage = 1,
                                 center_hexagon = NULL,
                                 get_hexagon = hexagon,
                                 tooltip = FALSE) {
  h3_hexagon_layer <- layer(
    rdeck,
    ...,
    type = "H3HexagonLayer",
    data = data,
    visible = visible,
    pickable = pickable,
    opacity = opacity,
    position_format = position_format,
    color_format = color_format,
    auto_highlight = auto_highlight,
    highlight_color = accessor(rlang::enquo(highlight_color), data),
    stroked = stroked,
    filled = filled,
    extruded = extruded,
    elevation_scale = elevation_scale,
    wireframe = wireframe,
    line_width_units = line_width_units,
    line_width_scale = line_width_scale,
    line_width_min_pixels = line_width_min_pixels,
    line_width_max_pixels = line_width_max_pixels,
    line_joint_rounded = line_joint_rounded,
    line_miter_limit = line_miter_limit,
    get_fill_color = accessor(rlang::enquo(get_fill_color), data),
    get_line_color = accessor(rlang::enquo(get_line_color), data),
    get_line_width = accessor(rlang::enquo(get_line_width), data),
    get_elevation = accessor_scale(rlang::enquo(get_elevation), data),
    material = material,
    high_precision = high_precision,
    coverage = coverage,
    center_hexagon = center_hexagon,
    get_hexagon = accessor(rlang::enquo(get_hexagon), data),
    tooltip = eval_tooltip(rlang::enquo(tooltip), data)
  )
  add_layer(rdeck, h3_hexagon_layer)
}

#' @rdname tile_layer
#' @autoglobal
#' @export
add_tile_layer <- function(rdeck,
                           ...,
                           id = "TileLayer",
                           data = NULL,
                           visible = TRUE,
                           pickable = FALSE,
                           opacity = 1,
                           position_format = "XYZ",
                           color_format = "RGBA",
                           auto_highlight = FALSE,
                           highlight_color = "#00008080",
                           get_tile_data = NULL,
                           extent = NULL,
                           tile_size = 512,
                           max_zoom = NULL,
                           min_zoom = 0,
                           max_cache_size = NULL,
                           max_cache_byte_size = NULL,
                           refinement_strategy = "best-available",
                           z_range = NULL,
                           max_requests = 6,
                           tooltip = FALSE) {
  tile_layer <- layer(
    rdeck,
    ...,
    type = "TileLayer",
    data = data,
    visible = visible,
    pickable = pickable,
    opacity = opacity,
    position_format = position_format,
    color_format = color_format,
    auto_highlight = auto_highlight,
    highlight_color = accessor(rlang::enquo(highlight_color), data),
    get_tile_data = get_tile_data,
    extent = extent,
    tile_size = tile_size,
    max_zoom = max_zoom,
    min_zoom = min_zoom,
    max_cache_size = max_cache_size,
    max_cache_byte_size = max_cache_byte_size,
    refinement_strategy = refinement_strategy,
    z_range = z_range,
    max_requests = max_requests,
    tooltip = eval_tooltip(rlang::enquo(tooltip), data)
  )
  add_layer(rdeck, tile_layer)
}

#' @rdname trips_layer
#' @autoglobal
#' @export
add_trips_layer <- function(rdeck,
                            ...,
                            id = "TripsLayer",
                            data = NULL,
                            visible = TRUE,
                            pickable = FALSE,
                            opacity = 1,
                            position_format = "XYZ",
                            color_format = "RGBA",
                            auto_highlight = FALSE,
                            highlight_color = "#00008080",
                            width_units = "meters",
                            width_scale = 1,
                            width_min_pixels = 0,
                            width_max_pixels = 9007199254740991,
                            rounded = FALSE,
                            miter_limit = 4,
                            billboard = FALSE,
                            get_path = path,
                            get_color = "#000000ff",
                            get_width = 1,
                            trail_length = 120,
                            current_time = 0,
                            get_timestamps = NULL,
                            tooltip = FALSE) {
  # auto-resolve geometry
  if (inherits(data, "sf")) {
    get_path <- as.name(attr(data, "sf_column"))
  }
  trips_layer <- layer(
    rdeck,
    ...,
    type = "TripsLayer",
    data = data,
    visible = visible,
    pickable = pickable,
    opacity = opacity,
    position_format = position_format,
    color_format = color_format,
    auto_highlight = auto_highlight,
    highlight_color = accessor(rlang::enquo(highlight_color), data),
    width_units = width_units,
    width_scale = width_scale,
    width_min_pixels = width_min_pixels,
    width_max_pixels = width_max_pixels,
    rounded = rounded,
    miter_limit = miter_limit,
    billboard = billboard,
    get_path = accessor(rlang::enquo(get_path), data),
    get_color = accessor_scale(rlang::enquo(get_color), data),
    get_width = accessor_scale(rlang::enquo(get_width), data),
    trail_length = trail_length,
    current_time = current_time,
    get_timestamps = accessor(rlang::enquo(get_timestamps), data),
    tooltip = eval_tooltip(rlang::enquo(tooltip), data)
  )
  add_layer(rdeck, trips_layer)
}

#' @rdname tile3d_layer
#' @autoglobal
#' @export
add_tile3d_layer <- function(rdeck,
                             ...,
                             id = "Tile3DLayer",
                             data = NULL,
                             visible = TRUE,
                             pickable = FALSE,
                             opacity = 1,
                             position_format = "XYZ",
                             color_format = "RGBA",
                             auto_highlight = FALSE,
                             highlight_color = "#00008080",
                             get_point_color = "#000000",
                             point_size = 1,
                             load_options = NULL,
                             loader = list(
                               id = "3d-tiles",
                               name = "3D Tiles",
                               version = "2.3.3",
                               extensions = c("cmpt", "pnts", "b3dm", "i3dm"),
                               mimeTypes = c("application/octet-stream"),
                               tests = c("cmpt", "pnts", "b3dm", "i3dm"),
                               parse = null,
                               options = list("3d-tiles" = list(
                                 loadGLTF = TRUE,
                                 decodeQuantizedPositions = FALSE,
                                 isTileset = "auto",
                                 tile = null,
                                 tileset = null,
                                 assetGltfUpAxis = null
                               ))
                             ),
                             tooltip = FALSE) {
  tile3d_layer <- layer(
    rdeck,
    ...,
    type = "Tile3DLayer",
    data = data,
    visible = visible,
    pickable = pickable,
    opacity = opacity,
    position_format = position_format,
    color_format = color_format,
    auto_highlight = auto_highlight,
    highlight_color = accessor(rlang::enquo(highlight_color), data),
    get_point_color = get_point_color,
    point_size = point_size,
    load_options = load_options,
    loader = loader,
    tooltip = eval_tooltip(rlang::enquo(tooltip), data)
  )
  add_layer(rdeck, tile3d_layer)
}

#' @rdname terrain_layer
#' @autoglobal
#' @export
add_terrain_layer <- function(rdeck,
                              ...,
                              id = "TerrainLayer",
                              data = NULL,
                              visible = TRUE,
                              pickable = FALSE,
                              opacity = 1,
                              position_format = "XYZ",
                              color_format = "RGBA",
                              auto_highlight = FALSE,
                              highlight_color = "#00008080",
                              get_tile_data = NULL,
                              extent = NULL,
                              tile_size = 512,
                              max_zoom = NULL,
                              min_zoom = 0,
                              max_cache_size = NULL,
                              max_cache_byte_size = NULL,
                              refinement_strategy = "best-available",
                              z_range = NULL,
                              max_requests = 6,
                              elevation_data = "",
                              texture = "",
                              mesh_max_error = 4,
                              bounds = NULL,
                              color = c(255, 255, 255),
                              elevation_decoder = list(
                                rScaler = 1,
                                gScaler = 0,
                                bScaler = 0,
                                offset = 0
                              ),
                              worker_url = NULL,
                              wireframe = FALSE,
                              material = TRUE,
                              tooltip = FALSE) {
  terrain_layer <- layer(
    rdeck,
    ...,
    type = "TerrainLayer",
    data = data,
    visible = visible,
    pickable = pickable,
    opacity = opacity,
    position_format = position_format,
    color_format = color_format,
    auto_highlight = auto_highlight,
    highlight_color = accessor(rlang::enquo(highlight_color), data),
    get_tile_data = get_tile_data,
    extent = extent,
    tile_size = tile_size,
    max_zoom = max_zoom,
    min_zoom = min_zoom,
    max_cache_size = max_cache_size,
    max_cache_byte_size = max_cache_byte_size,
    refinement_strategy = refinement_strategy,
    z_range = z_range,
    max_requests = max_requests,
    elevation_data = elevation_data,
    texture = texture,
    mesh_max_error = mesh_max_error,
    bounds = bounds,
    color = color,
    elevation_decoder = elevation_decoder,
    worker_url = worker_url,
    wireframe = wireframe,
    material = material,
    tooltip = eval_tooltip(rlang::enquo(tooltip), data)
  )
  add_layer(rdeck, terrain_layer)
}

#' @rdname mvt_layer
#' @autoglobal
#' @export
add_mvt_layer <- function(rdeck,
                          ...,
                          id = "MVTLayer",
                          data = NULL,
                          visible = TRUE,
                          pickable = FALSE,
                          opacity = 1,
                          position_format = "XYZ",
                          color_format = "RGBA",
                          auto_highlight = FALSE,
                          highlight_color = "#00008080",
                          get_tile_data = NULL,
                          extent = NULL,
                          tile_size = 512,
                          max_zoom = NULL,
                          min_zoom = 0,
                          max_cache_size = NULL,
                          max_cache_byte_size = NULL,
                          refinement_strategy = "best-available",
                          z_range = NULL,
                          max_requests = 6,
                          unique_id_property = "",
                          highlighted_feature_id = NULL,
                          tooltip = FALSE) {
  mvt_layer <- layer(
    rdeck,
    ...,
    type = "MVTLayer",
    data = data,
    visible = visible,
    pickable = pickable,
    opacity = opacity,
    position_format = position_format,
    color_format = color_format,
    auto_highlight = auto_highlight,
    highlight_color = accessor(rlang::enquo(highlight_color), data),
    get_tile_data = get_tile_data,
    extent = extent,
    tile_size = tile_size,
    max_zoom = max_zoom,
    min_zoom = min_zoom,
    max_cache_size = max_cache_size,
    max_cache_byte_size = max_cache_byte_size,
    refinement_strategy = refinement_strategy,
    z_range = z_range,
    max_requests = max_requests,
    unique_id_property = unique_id_property,
    highlighted_feature_id = highlighted_feature_id,
    tooltip = eval_tooltip(rlang::enquo(tooltip), data)
  )
  add_layer(rdeck, mvt_layer)
}

#' @rdname simple_mesh_layer
#' @autoglobal
#' @export
add_simple_mesh_layer <- function(rdeck,
                                  ...,
                                  id = "SimpleMeshLayer",
                                  data = NULL,
                                  visible = TRUE,
                                  pickable = FALSE,
                                  opacity = 1,
                                  position_format = "XYZ",
                                  color_format = "RGBA",
                                  auto_highlight = FALSE,
                                  highlight_color = "#00008080",
                                  mesh = NULL,
                                  texture = NULL,
                                  size_scale = 1,
                                  wireframe = FALSE,
                                  material = TRUE,
                                  get_position = position,
                                  get_color = "#000000ff",
                                  get_orientation = c(0, 0, 0),
                                  get_scale = c(1, 1, 1),
                                  get_translation = c(0, 0, 0),
                                  get_transform_matrix = NULL,
                                  tooltip = FALSE) {
  # auto-resolve geometry
  if (inherits(data, "sf")) {
    get_position <- as.name(attr(data, "sf_column"))
  }
  simple_mesh_layer <- layer(
    rdeck,
    ...,
    type = "SimpleMeshLayer",
    data = data,
    visible = visible,
    pickable = pickable,
    opacity = opacity,
    position_format = position_format,
    color_format = color_format,
    auto_highlight = auto_highlight,
    highlight_color = accessor(rlang::enquo(highlight_color), data),
    mesh = mesh,
    texture = texture,
    size_scale = size_scale,
    wireframe = wireframe,
    material = material,
    get_position = accessor(rlang::enquo(get_position), data),
    get_color = accessor_scale(rlang::enquo(get_color), data),
    get_orientation = accessor(rlang::enquo(get_orientation), data),
    get_scale = accessor(rlang::enquo(get_scale), data),
    get_translation = accessor(rlang::enquo(get_translation), data),
    get_transform_matrix = accessor(rlang::enquo(get_transform_matrix), data),
    tooltip = eval_tooltip(rlang::enquo(tooltip), data)
  )
  add_layer(rdeck, simple_mesh_layer)
}

#' @rdname scenegraph_layer
#' @autoglobal
#' @export
add_scenegraph_layer <- function(rdeck,
                                 ...,
                                 id = "ScenegraphLayer",
                                 data = NULL,
                                 visible = TRUE,
                                 pickable = FALSE,
                                 opacity = 1,
                                 position_format = "XYZ",
                                 color_format = "RGBA",
                                 auto_highlight = FALSE,
                                 highlight_color = "#00008080",
                                 scenegraph = NULL,
                                 get_scene = NULL,
                                 get_animator = NULL,
                                 size_scale = 1,
                                 size_min_pixels = 0,
                                 size_max_pixels = 9007199254740991,
                                 get_position = position,
                                 get_color = "#ffffffff",
                                 get_orientation = c(0, 0, 0),
                                 get_scale = c(1, 1, 1),
                                 get_translation = c(0, 0, 0),
                                 get_transform_matrix = NULL,
                                 tooltip = FALSE) {
  # auto-resolve geometry
  if (inherits(data, "sf")) {
    get_position <- as.name(attr(data, "sf_column"))
  }
  scenegraph_layer <- layer(
    rdeck,
    ...,
    type = "ScenegraphLayer",
    data = data,
    visible = visible,
    pickable = pickable,
    opacity = opacity,
    position_format = position_format,
    color_format = color_format,
    auto_highlight = auto_highlight,
    highlight_color = accessor(rlang::enquo(highlight_color), data),
    scenegraph = scenegraph,
    get_scene = get_scene,
    get_animator = get_animator,
    size_scale = size_scale,
    size_min_pixels = size_min_pixels,
    size_max_pixels = size_max_pixels,
    get_position = accessor(rlang::enquo(get_position), data),
    get_color = accessor_scale(rlang::enquo(get_color), data),
    get_orientation = accessor(rlang::enquo(get_orientation), data),
    get_scale = accessor(rlang::enquo(get_scale), data),
    get_translation = accessor(rlang::enquo(get_translation), data),
    get_transform_matrix = accessor(rlang::enquo(get_transform_matrix), data),
    tooltip = eval_tooltip(rlang::enquo(tooltip), data)
  )
  add_layer(rdeck, scenegraph_layer)
}
