# Generated by rdeck: do not edit by hand
# deck.gl version: 8.6.4

# validate aggregation
validate_aggregation <- function(layer) {
  UseMethod("validate_aggregation")
}
validate_aggregation.default <- function(layer) {
  aggregation <- layer$aggregation
  assert_not_null(aggregation)
}

# validate alpha_cutoff
validate_alpha_cutoff <- function(layer) {
  UseMethod("validate_alpha_cutoff")
}
validate_alpha_cutoff.default <- function(layer) {
  alpha_cutoff <- layer$alpha_cutoff
  assert_not_null(alpha_cutoff)
  assert_type(alpha_cutoff, c("integer", "numeric"))
  assert_finite(alpha_cutoff)
  assert_range(alpha_cutoff, 0, 1)
}

# validate angle
validate_angle <- function(layer) {
  UseMethod("validate_angle")
}
validate_angle.default <- function(layer) {
  angle <- layer$angle
  assert_not_null(angle)
  assert_type(angle, c("integer", "numeric"))
  assert_finite(angle)
}

# validate animation_speed
validate_animation_speed <- function(layer) {
  UseMethod("validate_animation_speed")
}
validate_animation_speed.default <- function(layer) {
  animation_speed <- layer$animation_speed
  assert_not_null(animation_speed)
  assert_type(animation_speed, c("integer", "numeric"))
  assert_finite(animation_speed)
  assert_range(animation_speed, 0, NULL)
}

# validate antialiasing
validate_antialiasing <- function(layer) {
  UseMethod("validate_antialiasing")
}
validate_antialiasing.default <- function(layer) {
  antialiasing <- layer$antialiasing
  assert_not_null(antialiasing)
  assert_type(antialiasing, "logical")
}

# validate auto_highlight
validate_auto_highlight <- function(layer) {
  UseMethod("validate_auto_highlight")
}
validate_auto_highlight.default <- function(layer) {
  auto_highlight <- layer$auto_highlight
  assert_not_null(auto_highlight)
  assert_type(auto_highlight, "logical")
}

# validate background
validate_background <- function(layer) {
  UseMethod("validate_background")
}
validate_background.default <- function(layer) {
  background <- layer$background
  assert_not_null(background)
  assert_type(background, "logical")
}

# validate background_padding
validate_background_padding <- function(layer) {
  UseMethod("validate_background_padding")
}
validate_background_padding.default <- function(layer) {
  background_padding <- layer$background_padding
  assert_not_null(background_padding)
}

# validate billboard
validate_billboard <- function(layer) {
  UseMethod("validate_billboard")
}
validate_billboard.default <- function(layer) {
  billboard <- layer$billboard
  assert_not_null(billboard)
  assert_type(billboard, "logical")
}

# validate binary
validate_binary <- function(layer) {
  UseMethod("validate_binary")
}
validate_binary.default <- function(layer) {
  binary <- layer$binary
  assert_not_null(binary)
  assert_type(binary, "logical")
}

# validate bounds
validate_bounds <- function(layer) {
  UseMethod("validate_bounds")
}
validate_bounds.default <- function(layer) {
  bounds <- layer$bounds
  if (is.null(bounds)) {
    return()
  }
}

# validate cap_rounded
validate_cap_rounded <- function(layer) {
  UseMethod("validate_cap_rounded")
}
validate_cap_rounded.default <- function(layer) {
  cap_rounded <- layer$cap_rounded
  assert_not_null(cap_rounded)
  assert_type(cap_rounded, "logical")
}

# validate cell_margin_pixels
validate_cell_margin_pixels <- function(layer) {
  UseMethod("validate_cell_margin_pixels")
}
validate_cell_margin_pixels.default <- function(layer) {
  cell_margin_pixels <- layer$cell_margin_pixels
  assert_not_null(cell_margin_pixels)
  assert_type(cell_margin_pixels, c("integer", "numeric"))
  assert_finite(cell_margin_pixels)
  assert_range(cell_margin_pixels, 0, 5)
}

# validate cell_size
validate_cell_size <- function(layer) {
  UseMethod("validate_cell_size")
}
validate_cell_size.default <- function(layer) {
  cell_size <- layer$cell_size
  assert_not_null(cell_size)
  assert_type(cell_size, c("integer", "numeric"))
  assert_finite(cell_size)
  assert_range(cell_size, 1, 1000)
}

# validate cell_size_pixels
validate_cell_size_pixels <- function(layer) {
  UseMethod("validate_cell_size_pixels")
}
validate_cell_size_pixels.default <- function(layer) {
  cell_size_pixels <- layer$cell_size_pixels
  assert_not_null(cell_size_pixels)
  assert_type(cell_size_pixels, c("integer", "numeric"))
  assert_finite(cell_size_pixels)
  assert_range(cell_size_pixels, 1, NULL)
}

# validate center_hexagon
validate_center_hexagon <- function(layer) {
  UseMethod("validate_center_hexagon")
}
validate_center_hexagon.default <- function(layer) {
  center_hexagon <- layer$center_hexagon
  if (is.null(center_hexagon)) {
    return()
  }
}

# validate color
validate_color <- function(layer) {
  UseMethod("validate_color")
}
validate_color.default <- function(layer) {
  color <- layer$color
  assert_not_null(color)
  assert_rgba(color)
}

# validate color_aggregation
validate_color_aggregation <- function(layer) {
  UseMethod("validate_color_aggregation")
}
validate_color_aggregation.default <- function(layer) {
  color_aggregation <- layer$color_aggregation
  assert_not_null(color_aggregation)
}

# validate color_domain
validate_color_domain <- function(layer) {
  UseMethod("validate_color_domain")
}
validate_color_domain.default <- function(layer) {
  color_domain <- layer$color_domain
  if (is.null(color_domain)) {
    return()
  }
}

# validate color_format
validate_color_format <- function(layer) {
  UseMethod("validate_color_format")
}
validate_color_format.default <- function(layer) {
  color_format <- layer$color_format
  assert_not_null(color_format)
}

# validate color_range
validate_color_range <- function(layer) {
  UseMethod("validate_color_range")
}
validate_color_range.default <- function(layer) {
  color_range <- layer$color_range
  assert_not_null(color_range)
  assert_rgba(color_range)
}

# validate color_scale_type
validate_color_scale_type <- function(layer) {
  UseMethod("validate_color_scale_type")
}
validate_color_scale_type.default <- function(layer) {
  color_scale_type <- layer$color_scale_type
  assert_not_null(color_scale_type)
}

# validate contours
validate_contours <- function(layer) {
  UseMethod("validate_contours")
}
validate_contours.default <- function(layer) {
  contours <- layer$contours
  assert_not_null(contours)
}

# validate coverage
validate_coverage <- function(layer) {
  UseMethod("validate_coverage")
}
validate_coverage.default <- function(layer) {
  coverage <- layer$coverage
  assert_not_null(coverage)
  assert_type(coverage, c("integer", "numeric"))
  assert_finite(coverage)
  assert_range(coverage, 0, 1)
}

# validate data
validate_data <- function(layer) {
  UseMethod("validate_data")
}
validate_data.default <- function(layer) {
  data <- layer$data
  if (is.null(data)) {
    return()
  }
}

# validate debounce_timeout
validate_debounce_timeout <- function(layer) {
  UseMethod("validate_debounce_timeout")
}
validate_debounce_timeout.default <- function(layer) {
  debounce_timeout <- layer$debounce_timeout
  assert_not_null(debounce_timeout)
  assert_type(debounce_timeout, c("integer", "numeric"))
  assert_finite(debounce_timeout)
  assert_range(debounce_timeout, 0, 1000)
}

# validate desaturate
validate_desaturate <- function(layer) {
  UseMethod("validate_desaturate")
}
validate_desaturate.default <- function(layer) {
  desaturate <- layer$desaturate
  assert_not_null(desaturate)
  assert_type(desaturate, c("integer", "numeric"))
  assert_finite(desaturate)
  assert_range(desaturate, 0, 1)
}

# validate disk_resolution
validate_disk_resolution <- function(layer) {
  UseMethod("validate_disk_resolution")
}
validate_disk_resolution.default <- function(layer) {
  disk_resolution <- layer$disk_resolution
  assert_not_null(disk_resolution)
  assert_type(disk_resolution, c("integer", "numeric"))
  assert_finite(disk_resolution)
  assert_range(disk_resolution, 4, NULL)
}

# validate elevation_aggregation
validate_elevation_aggregation <- function(layer) {
  UseMethod("validate_elevation_aggregation")
}
validate_elevation_aggregation.default <- function(layer) {
  elevation_aggregation <- layer$elevation_aggregation
  assert_not_null(elevation_aggregation)
}

# validate elevation_data
validate_elevation_data <- function(layer) {
  UseMethod("validate_elevation_data")
}
validate_elevation_data.default <- function(layer) {
  elevation_data <- layer$elevation_data
  if (is.null(elevation_data)) {
    return()
  }
}

# validate elevation_decoder
validate_elevation_decoder <- function(layer) {
  UseMethod("validate_elevation_decoder")
}
validate_elevation_decoder.default <- function(layer) {
  elevation_decoder <- layer$elevation_decoder
  assert_not_null(elevation_decoder)
}

# validate elevation_domain
validate_elevation_domain <- function(layer) {
  UseMethod("validate_elevation_domain")
}
validate_elevation_domain.default <- function(layer) {
  elevation_domain <- layer$elevation_domain
  if (is.null(elevation_domain)) {
    return()
  }
}

# validate elevation_lower_percentile
validate_elevation_lower_percentile <- function(layer) {
  UseMethod("validate_elevation_lower_percentile")
}
validate_elevation_lower_percentile.default <- function(layer) {
  elevation_lower_percentile <- layer$elevation_lower_percentile
  assert_not_null(elevation_lower_percentile)
  assert_type(elevation_lower_percentile, c("integer", "numeric"))
  assert_finite(elevation_lower_percentile)
  assert_range(elevation_lower_percentile, 0, 100)
}

# validate elevation_range
validate_elevation_range <- function(layer) {
  UseMethod("validate_elevation_range")
}
validate_elevation_range.default <- function(layer) {
  elevation_range <- layer$elevation_range
  assert_not_null(elevation_range)
}

# validate elevation_scale
validate_elevation_scale <- function(layer) {
  UseMethod("validate_elevation_scale")
}
validate_elevation_scale.default <- function(layer) {
  elevation_scale <- layer$elevation_scale
  assert_not_null(elevation_scale)
  assert_type(elevation_scale, c("integer", "numeric"))
  assert_finite(elevation_scale)
  assert_range(elevation_scale, 0, NULL)
}

# validate elevation_scale_type
validate_elevation_scale_type <- function(layer) {
  UseMethod("validate_elevation_scale_type")
}
validate_elevation_scale_type.default <- function(layer) {
  elevation_scale_type <- layer$elevation_scale_type
  assert_not_null(elevation_scale_type)
}

# validate elevation_upper_percentile
validate_elevation_upper_percentile <- function(layer) {
  UseMethod("validate_elevation_upper_percentile")
}
validate_elevation_upper_percentile.default <- function(layer) {
  elevation_upper_percentile <- layer$elevation_upper_percentile
  assert_not_null(elevation_upper_percentile)
  assert_type(elevation_upper_percentile, c("integer", "numeric"))
  assert_finite(elevation_upper_percentile)
  assert_range(elevation_upper_percentile, 0, 100)
}

# validate extent
validate_extent <- function(layer) {
  UseMethod("validate_extent")
}
validate_extent.default <- function(layer) {
  extent <- layer$extent
  if (is.null(extent)) {
    return()
  }
}

# validate extruded
validate_extruded <- function(layer) {
  UseMethod("validate_extruded")
}
validate_extruded.default <- function(layer) {
  extruded <- layer$extruded
  assert_not_null(extruded)
  assert_type(extruded, "logical")
}

# validate fade_trail
validate_fade_trail <- function(layer) {
  UseMethod("validate_fade_trail")
}
validate_fade_trail.default <- function(layer) {
  fade_trail <- layer$fade_trail
  assert_not_null(fade_trail)
  assert_type(fade_trail, "logical")
}

# validate filled
validate_filled <- function(layer) {
  UseMethod("validate_filled")
}
validate_filled.default <- function(layer) {
  filled <- layer$filled
  assert_not_null(filled)
  assert_type(filled, "logical")
}

# validate font_family
validate_font_family <- function(layer) {
  UseMethod("validate_font_family")
}
validate_font_family.default <- function(layer) {
  font_family <- layer$font_family
  assert_not_null(font_family)
}

# validate font_settings
validate_font_settings <- function(layer) {
  UseMethod("validate_font_settings")
}
validate_font_settings.default <- function(layer) {
  font_settings <- layer$font_settings
  assert_not_null(font_settings)
}

# validate font_weight
validate_font_weight <- function(layer) {
  UseMethod("validate_font_weight")
}
validate_font_weight.default <- function(layer) {
  font_weight <- layer$font_weight
  assert_not_null(font_weight)
}

# validate get_alignment_baseline
validate_get_alignment_baseline <- function(layer) {
  UseMethod("validate_get_alignment_baseline")
}
validate_get_alignment_baseline.default <- function(layer) {
  get_alignment_baseline <- layer$get_alignment_baseline
  assert_not_null(get_alignment_baseline)
  if (!inherits(get_alignment_baseline, "accessor")) {
    assert_type(get_alignment_baseline, "character")
    assert_scalar(get_alignment_baseline)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_alignment_baseline$col, data)

    assert_type(data[[get_alignment_baseline$col]], "character")
  }
}

# validate get_angle
validate_get_angle <- function(layer) {
  UseMethod("validate_get_angle")
}
validate_get_angle.default <- function(layer) {
  get_angle <- layer$get_angle
  assert_not_null(get_angle)
  if (!inherits(get_angle, "accessor")) {
    assert_type(get_angle, c("integer", "numeric"))
    assert_finite(get_angle)
    assert_scalar(get_angle)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_angle$col, data)

    assert_type(data[[get_angle$col]], c("integer", "numeric"))
    assert_finite(data[[get_angle$col]])
  }
}

# validate get_animator
validate_get_animator <- function(layer) {
  UseMethod("validate_get_animator")
}
validate_get_animator.default <- function(layer) {
  get_animator <- layer$get_animator
  if (is.null(get_animator)) {
    return()
  }
}

# validate get_background_color
validate_get_background_color <- function(layer) {
  UseMethod("validate_get_background_color")
}
validate_get_background_color.default <- function(layer) {
  get_background_color <- layer$get_background_color
  assert_not_null(get_background_color)
  if (!inherits(get_background_color, "accessor")) {
    assert_rgba(get_background_color)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_background_color$col, data)
    if (!inherits(get_background_color, "accessor_scale")) {
      assert_rgba(data[[get_background_color$col]])
    }
  }
  if (inherits(get_background_color, "accessor_scale")) {
    assert_scalable_is_color(get_background_color)
    validate_col(get_background_color, data)
  }
}

# validate get_border_color
validate_get_border_color <- function(layer) {
  UseMethod("validate_get_border_color")
}
validate_get_border_color.default <- function(layer) {
  get_border_color <- layer$get_border_color
  assert_not_null(get_border_color)
  if (!inherits(get_border_color, "accessor")) {
    assert_rgba(get_border_color)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_border_color$col, data)
    if (!inherits(get_border_color, "accessor_scale")) {
      assert_rgba(data[[get_border_color$col]])
    }
  }
  if (inherits(get_border_color, "accessor_scale")) {
    assert_scalable_is_color(get_border_color)
    validate_col(get_border_color, data)
  }
}

# validate get_border_width
validate_get_border_width <- function(layer) {
  UseMethod("validate_get_border_width")
}
validate_get_border_width.default <- function(layer) {
  get_border_width <- layer$get_border_width
  assert_not_null(get_border_width)
  if (!inherits(get_border_width, "accessor")) {
    assert_type(get_border_width, c("integer", "numeric"))
    assert_finite(get_border_width)
    assert_scalar(get_border_width)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_border_width$col, data)
    if (!inherits(get_border_width, "accessor_scale")) {
      assert_type(data[[get_border_width$col]], c("integer", "numeric"))
      assert_finite(data[[get_border_width$col]])
    }
  }
  if (inherits(get_border_width, "accessor_scale")) {
    assert_scalable_is_numeric(get_border_width)
    validate_col(get_border_width, data)
  }
}

# validate get_color
validate_get_color <- function(layer) {
  UseMethod("validate_get_color")
}
validate_get_color.default <- function(layer) {
  get_color <- layer$get_color
  assert_not_null(get_color)
  if (!inherits(get_color, "accessor")) {
    assert_rgba(get_color)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_color$col, data)
    if (!inherits(get_color, "accessor_scale")) {
      assert_rgba(data[[get_color$col]])
    }
  }
  if (inherits(get_color, "accessor_scale")) {
    assert_scalable_is_color(get_color)
    validate_col(get_color, data)
  }
}

# validate get_color_value
validate_get_color_value <- function(layer) {
  UseMethod("validate_get_color_value")
}
validate_get_color_value.default <- function(layer) {
  get_color_value <- layer$get_color_value
  if (is.null(get_color_value)) {
    return()
  }
}

# validate get_color_weight
validate_get_color_weight <- function(layer) {
  UseMethod("validate_get_color_weight")
}
validate_get_color_weight.default <- function(layer) {
  get_color_weight <- layer$get_color_weight
  assert_not_null(get_color_weight)
  if (!inherits(get_color_weight, "accessor")) {
    assert_type(get_color_weight, c("integer", "numeric"))
    assert_finite(get_color_weight)
    assert_scalar(get_color_weight)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_color_weight$col, data)
    if (!inherits(get_color_weight, "accessor_scale")) {
      assert_type(data[[get_color_weight$col]], c("integer", "numeric"))
      assert_finite(data[[get_color_weight$col]])
    }
  }
  if (inherits(get_color_weight, "accessor_scale")) {
    assert_scalable_is_numeric(get_color_weight)
    validate_col(get_color_weight, data)
  }
}

# validate get_elevation
validate_get_elevation <- function(layer) {
  UseMethod("validate_get_elevation")
}
validate_get_elevation.default <- function(layer) {
  get_elevation <- layer$get_elevation
  assert_not_null(get_elevation)
  if (!inherits(get_elevation, "accessor")) {
    assert_type(get_elevation, c("integer", "numeric"))
    assert_finite(get_elevation)
    assert_scalar(get_elevation)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_elevation$col, data)
    if (!inherits(get_elevation, "accessor_scale")) {
      assert_type(data[[get_elevation$col]], c("integer", "numeric"))
      assert_finite(data[[get_elevation$col]])
    }
  }
  if (inherits(get_elevation, "accessor_scale")) {
    assert_scalable_is_numeric(get_elevation)
    validate_col(get_elevation, data)
  }
}

# validate get_elevation_value
validate_get_elevation_value <- function(layer) {
  UseMethod("validate_get_elevation_value")
}
validate_get_elevation_value.default <- function(layer) {
  get_elevation_value <- layer$get_elevation_value
  if (is.null(get_elevation_value)) {
    return()
  }
}

# validate get_elevation_weight
validate_get_elevation_weight <- function(layer) {
  UseMethod("validate_get_elevation_weight")
}
validate_get_elevation_weight.default <- function(layer) {
  get_elevation_weight <- layer$get_elevation_weight
  assert_not_null(get_elevation_weight)
  if (!inherits(get_elevation_weight, "accessor")) {
    assert_type(get_elevation_weight, c("integer", "numeric"))
    assert_finite(get_elevation_weight)
    assert_scalar(get_elevation_weight)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_elevation_weight$col, data)
    if (!inherits(get_elevation_weight, "accessor_scale")) {
      assert_type(data[[get_elevation_weight$col]], c("integer", "numeric"))
      assert_finite(data[[get_elevation_weight$col]])
    }
  }
  if (inherits(get_elevation_weight, "accessor_scale")) {
    assert_scalable_is_numeric(get_elevation_weight)
    validate_col(get_elevation_weight, data)
  }
}

# validate get_fill_color
validate_get_fill_color <- function(layer) {
  UseMethod("validate_get_fill_color")
}
validate_get_fill_color.default <- function(layer) {
  get_fill_color <- layer$get_fill_color
  assert_not_null(get_fill_color)
  if (!inherits(get_fill_color, "accessor")) {
    assert_rgba(get_fill_color)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_fill_color$col, data)
    if (!inherits(get_fill_color, "accessor_scale")) {
      assert_rgba(data[[get_fill_color$col]])
    }
  }
  if (inherits(get_fill_color, "accessor_scale")) {
    assert_scalable_is_color(get_fill_color)
    validate_col(get_fill_color, data)
  }
}

# validate get_height
validate_get_height <- function(layer) {
  UseMethod("validate_get_height")
}
validate_get_height.default <- function(layer) {
  get_height <- layer$get_height
  assert_not_null(get_height)
  if (!inherits(get_height, "accessor")) {
    assert_type(get_height, c("integer", "numeric"))
    assert_finite(get_height)
    assert_scalar(get_height)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_height$col, data)
    if (!inherits(get_height, "accessor_scale")) {
      assert_type(data[[get_height$col]], c("integer", "numeric"))
      assert_finite(data[[get_height$col]])
    }
  }
  if (inherits(get_height, "accessor_scale")) {
    assert_scalable_is_numeric(get_height)
    validate_col(get_height, data)
  }
}

# validate get_hexagon
validate_get_hexagon <- function(layer) {
  UseMethod("validate_get_hexagon")
}
validate_get_hexagon.default <- function(layer) {
  get_hexagon <- layer$get_hexagon
  assert_not_null(get_hexagon)
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_hexagon$col, data)
  }
}

# validate get_hexagons
validate_get_hexagons <- function(layer) {
  UseMethod("validate_get_hexagons")
}
validate_get_hexagons.default <- function(layer) {
  get_hexagons <- layer$get_hexagons
  assert_not_null(get_hexagons)
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_hexagons$col, data)
  }
}

# validate get_icon
validate_get_icon <- function(layer) {
  UseMethod("validate_get_icon")
}
validate_get_icon.default <- function(layer) {
  get_icon <- layer$get_icon
  assert_not_null(get_icon)
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_icon$col, data)
  }
}

# validate get_icon_angle
validate_get_icon_angle <- function(layer) {
  UseMethod("validate_get_icon_angle")
}
validate_get_icon_angle.default <- function(layer) {
  get_icon_angle <- layer$get_icon_angle
  assert_not_null(get_icon_angle)
  if (!inherits(get_icon_angle, "accessor")) {
    assert_type(get_icon_angle, c("integer", "numeric"))
    assert_finite(get_icon_angle)
    assert_scalar(get_icon_angle)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_icon_angle$col, data)

    assert_type(data[[get_icon_angle$col]], c("integer", "numeric"))
    assert_finite(data[[get_icon_angle$col]])
  }
}

# validate get_icon_color
validate_get_icon_color <- function(layer) {
  UseMethod("validate_get_icon_color")
}
validate_get_icon_color.default <- function(layer) {
  get_icon_color <- layer$get_icon_color
  assert_not_null(get_icon_color)
  if (!inherits(get_icon_color, "accessor")) {
    assert_rgba(get_icon_color)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_icon_color$col, data)
    if (!inherits(get_icon_color, "accessor_scale")) {
      assert_rgba(data[[get_icon_color$col]])
    }
  }
  if (inherits(get_icon_color, "accessor_scale")) {
    assert_scalable_is_color(get_icon_color)
    validate_col(get_icon_color, data)
  }
}

# validate get_icon_pixel_offset
validate_get_icon_pixel_offset <- function(layer) {
  UseMethod("validate_get_icon_pixel_offset")
}
validate_get_icon_pixel_offset.default <- function(layer) {
  get_icon_pixel_offset <- layer$get_icon_pixel_offset
  assert_not_null(get_icon_pixel_offset)
  if (!inherits(get_icon_pixel_offset, "accessor")) {
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_icon_pixel_offset$col, data)
  }
}

# validate get_icon_size
validate_get_icon_size <- function(layer) {
  UseMethod("validate_get_icon_size")
}
validate_get_icon_size.default <- function(layer) {
  get_icon_size <- layer$get_icon_size
  assert_not_null(get_icon_size)
  if (!inherits(get_icon_size, "accessor")) {
    assert_type(get_icon_size, c("integer", "numeric"))
    assert_finite(get_icon_size)
    assert_scalar(get_icon_size)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_icon_size$col, data)
    if (!inherits(get_icon_size, "accessor_scale")) {
      assert_type(data[[get_icon_size$col]], c("integer", "numeric"))
      assert_finite(data[[get_icon_size$col]])
    }
  }
  if (inherits(get_icon_size, "accessor_scale")) {
    assert_scalable_is_numeric(get_icon_size)
    validate_col(get_icon_size, data)
  }
}

# validate get_line_color
validate_get_line_color <- function(layer) {
  UseMethod("validate_get_line_color")
}
validate_get_line_color.default <- function(layer) {
  get_line_color <- layer$get_line_color
  assert_not_null(get_line_color)
  if (!inherits(get_line_color, "accessor")) {
    assert_rgba(get_line_color)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_line_color$col, data)
    if (!inherits(get_line_color, "accessor_scale")) {
      assert_rgba(data[[get_line_color$col]])
    }
  }
  if (inherits(get_line_color, "accessor_scale")) {
    assert_scalable_is_color(get_line_color)
    validate_col(get_line_color, data)
  }
}

# validate get_line_width
validate_get_line_width <- function(layer) {
  UseMethod("validate_get_line_width")
}
validate_get_line_width.default <- function(layer) {
  get_line_width <- layer$get_line_width
  assert_not_null(get_line_width)
  if (!inherits(get_line_width, "accessor")) {
    assert_type(get_line_width, c("integer", "numeric"))
    assert_finite(get_line_width)
    assert_scalar(get_line_width)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_line_width$col, data)
    if (!inherits(get_line_width, "accessor_scale")) {
      assert_type(data[[get_line_width$col]], c("integer", "numeric"))
      assert_finite(data[[get_line_width$col]])
    }
  }
  if (inherits(get_line_width, "accessor_scale")) {
    assert_scalable_is_numeric(get_line_width)
    validate_col(get_line_width, data)
  }
}

# validate get_normal
validate_get_normal <- function(layer) {
  UseMethod("validate_get_normal")
}
validate_get_normal.default <- function(layer) {
  get_normal <- layer$get_normal
  assert_not_null(get_normal)
  if (!inherits(get_normal, "accessor")) {
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_normal$col, data)
  }
}

# validate get_orientation
validate_get_orientation <- function(layer) {
  UseMethod("validate_get_orientation")
}
validate_get_orientation.default <- function(layer) {
  get_orientation <- layer$get_orientation
  assert_not_null(get_orientation)
  if (!inherits(get_orientation, "accessor")) {
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_orientation$col, data)
  }
}

# validate get_path
validate_get_path <- function(layer) {
  UseMethod("validate_get_path")
}
validate_get_path.default <- function(layer) {
  get_path <- layer$get_path
  assert_not_null(get_path)
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_path$col, data)
  }
}

# validate get_pixel_offset
validate_get_pixel_offset <- function(layer) {
  UseMethod("validate_get_pixel_offset")
}
validate_get_pixel_offset.default <- function(layer) {
  get_pixel_offset <- layer$get_pixel_offset
  assert_not_null(get_pixel_offset)
  if (!inherits(get_pixel_offset, "accessor")) {
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_pixel_offset$col, data)
  }
}

# validate get_point_color
validate_get_point_color <- function(layer) {
  UseMethod("validate_get_point_color")
}
validate_get_point_color.default <- function(layer) {
  get_point_color <- layer$get_point_color
  assert_not_null(get_point_color)
  if (!inherits(get_point_color, "accessor")) {
    assert_rgba(get_point_color)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_point_color$col, data)
    if (!inherits(get_point_color, "accessor_scale")) {
      assert_rgba(data[[get_point_color$col]])
    }
  }
  if (inherits(get_point_color, "accessor_scale")) {
    assert_scalable_is_color(get_point_color)
    validate_col(get_point_color, data)
  }
}

# validate get_point_radius
validate_get_point_radius <- function(layer) {
  UseMethod("validate_get_point_radius")
}
validate_get_point_radius.default <- function(layer) {
  get_point_radius <- layer$get_point_radius
  assert_not_null(get_point_radius)
  if (!inherits(get_point_radius, "accessor")) {
    assert_type(get_point_radius, c("integer", "numeric"))
    assert_finite(get_point_radius)
    assert_scalar(get_point_radius)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_point_radius$col, data)
    if (!inherits(get_point_radius, "accessor_scale")) {
      assert_type(data[[get_point_radius$col]], c("integer", "numeric"))
      assert_finite(data[[get_point_radius$col]])
    }
  }
  if (inherits(get_point_radius, "accessor_scale")) {
    assert_scalable_is_numeric(get_point_radius)
    validate_col(get_point_radius, data)
  }
}

# validate get_polygon
validate_get_polygon <- function(layer) {
  UseMethod("validate_get_polygon")
}
validate_get_polygon.default <- function(layer) {
  get_polygon <- layer$get_polygon
  assert_not_null(get_polygon)
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_polygon$col, data)
  }
}

# validate get_position
validate_get_position <- function(layer) {
  UseMethod("validate_get_position")
}
validate_get_position.default <- function(layer) {
  get_position <- layer$get_position
  assert_not_null(get_position)
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_position$col, data)
  }
}

# validate get_radius
validate_get_radius <- function(layer) {
  UseMethod("validate_get_radius")
}
validate_get_radius.default <- function(layer) {
  get_radius <- layer$get_radius
  assert_not_null(get_radius)
  if (!inherits(get_radius, "accessor")) {
    assert_type(get_radius, c("integer", "numeric"))
    assert_finite(get_radius)
    assert_scalar(get_radius)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_radius$col, data)
    if (!inherits(get_radius, "accessor_scale")) {
      assert_type(data[[get_radius$col]], c("integer", "numeric"))
      assert_finite(data[[get_radius$col]])
    }
  }
  if (inherits(get_radius, "accessor_scale")) {
    assert_scalable_is_numeric(get_radius)
    validate_col(get_radius, data)
  }
}

# validate get_s2_token
validate_get_s2_token <- function(layer) {
  UseMethod("validate_get_s2_token")
}
validate_get_s2_token.default <- function(layer) {
  get_s2_token <- layer$get_s2_token
  assert_not_null(get_s2_token)
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_s2_token$col, data)
  }
}

# validate get_scale
validate_get_scale <- function(layer) {
  UseMethod("validate_get_scale")
}
validate_get_scale.default <- function(layer) {
  get_scale <- layer$get_scale
  assert_not_null(get_scale)
  if (!inherits(get_scale, "accessor")) {
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_scale$col, data)
  }
}

# validate get_scene
validate_get_scene <- function(layer) {
  UseMethod("validate_get_scene")
}
validate_get_scene.default <- function(layer) {
  get_scene <- layer$get_scene
  if (is.null(get_scene)) {
    return()
  }
}

# validate get_size
validate_get_size <- function(layer) {
  UseMethod("validate_get_size")
}
validate_get_size.default <- function(layer) {
  get_size <- layer$get_size
  assert_not_null(get_size)
  if (!inherits(get_size, "accessor")) {
    assert_type(get_size, c("integer", "numeric"))
    assert_finite(get_size)
    assert_scalar(get_size)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_size$col, data)
    if (!inherits(get_size, "accessor_scale")) {
      assert_type(data[[get_size$col]], c("integer", "numeric"))
      assert_finite(data[[get_size$col]])
    }
  }
  if (inherits(get_size, "accessor_scale")) {
    assert_scalable_is_numeric(get_size)
    validate_col(get_size, data)
  }
}

# validate get_source_color
validate_get_source_color <- function(layer) {
  UseMethod("validate_get_source_color")
}
validate_get_source_color.default <- function(layer) {
  get_source_color <- layer$get_source_color
  assert_not_null(get_source_color)
  if (!inherits(get_source_color, "accessor")) {
    assert_rgba(get_source_color)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_source_color$col, data)
    if (!inherits(get_source_color, "accessor_scale")) {
      assert_rgba(data[[get_source_color$col]])
    }
  }
  if (inherits(get_source_color, "accessor_scale")) {
    assert_scalable_is_color(get_source_color)
    validate_col(get_source_color, data)
  }
}

# validate get_source_position
validate_get_source_position <- function(layer) {
  UseMethod("validate_get_source_position")
}
validate_get_source_position.default <- function(layer) {
  get_source_position <- layer$get_source_position
  assert_not_null(get_source_position)
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_source_position$col, data)
  }
}

# validate get_target_color
validate_get_target_color <- function(layer) {
  UseMethod("validate_get_target_color")
}
validate_get_target_color.default <- function(layer) {
  get_target_color <- layer$get_target_color
  assert_not_null(get_target_color)
  if (!inherits(get_target_color, "accessor")) {
    assert_rgba(get_target_color)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_target_color$col, data)
    if (!inherits(get_target_color, "accessor_scale")) {
      assert_rgba(data[[get_target_color$col]])
    }
  }
  if (inherits(get_target_color, "accessor_scale")) {
    assert_scalable_is_color(get_target_color)
    validate_col(get_target_color, data)
  }
}

# validate get_target_position
validate_get_target_position <- function(layer) {
  UseMethod("validate_get_target_position")
}
validate_get_target_position.default <- function(layer) {
  get_target_position <- layer$get_target_position
  assert_not_null(get_target_position)
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_target_position$col, data)
  }
}

# validate get_text
validate_get_text <- function(layer) {
  UseMethod("validate_get_text")
}
validate_get_text.default <- function(layer) {
  get_text <- layer$get_text
  assert_not_null(get_text)
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_text$col, data)
  }
}

# validate get_text_alignment_baseline
validate_get_text_alignment_baseline <- function(layer) {
  UseMethod("validate_get_text_alignment_baseline")
}
validate_get_text_alignment_baseline.default <- function(layer) {
  get_text_alignment_baseline <- layer$get_text_alignment_baseline
  assert_not_null(get_text_alignment_baseline)
  if (!inherits(get_text_alignment_baseline, "accessor")) {
    assert_type(get_text_alignment_baseline, "character")
    assert_scalar(get_text_alignment_baseline)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_text_alignment_baseline$col, data)

    assert_type(data[[get_text_alignment_baseline$col]], "character")
  }
}

# validate get_text_anchor
validate_get_text_anchor <- function(layer) {
  UseMethod("validate_get_text_anchor")
}
validate_get_text_anchor.default <- function(layer) {
  get_text_anchor <- layer$get_text_anchor
  assert_not_null(get_text_anchor)
  if (!inherits(get_text_anchor, "accessor")) {
    assert_type(get_text_anchor, "character")
    assert_scalar(get_text_anchor)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_text_anchor$col, data)

    assert_type(data[[get_text_anchor$col]], "character")
  }
}

# validate get_text_angle
validate_get_text_angle <- function(layer) {
  UseMethod("validate_get_text_angle")
}
validate_get_text_angle.default <- function(layer) {
  get_text_angle <- layer$get_text_angle
  assert_not_null(get_text_angle)
  if (!inherits(get_text_angle, "accessor")) {
    assert_type(get_text_angle, c("integer", "numeric"))
    assert_finite(get_text_angle)
    assert_scalar(get_text_angle)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_text_angle$col, data)

    assert_type(data[[get_text_angle$col]], c("integer", "numeric"))
    assert_finite(data[[get_text_angle$col]])
  }
}

# validate get_text_background_color
validate_get_text_background_color <- function(layer) {
  UseMethod("validate_get_text_background_color")
}
validate_get_text_background_color.default <- function(layer) {
  get_text_background_color <- layer$get_text_background_color
  assert_not_null(get_text_background_color)
  if (!inherits(get_text_background_color, "accessor")) {
    assert_rgba(get_text_background_color)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_text_background_color$col, data)
    if (!inherits(get_text_background_color, "accessor_scale")) {
      assert_rgba(data[[get_text_background_color$col]])
    }
  }
  if (inherits(get_text_background_color, "accessor_scale")) {
    assert_scalable_is_color(get_text_background_color)
    validate_col(get_text_background_color, data)
  }
}

# validate get_text_border_color
validate_get_text_border_color <- function(layer) {
  UseMethod("validate_get_text_border_color")
}
validate_get_text_border_color.default <- function(layer) {
  get_text_border_color <- layer$get_text_border_color
  assert_not_null(get_text_border_color)
  if (!inherits(get_text_border_color, "accessor")) {
    assert_rgba(get_text_border_color)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_text_border_color$col, data)
    if (!inherits(get_text_border_color, "accessor_scale")) {
      assert_rgba(data[[get_text_border_color$col]])
    }
  }
  if (inherits(get_text_border_color, "accessor_scale")) {
    assert_scalable_is_color(get_text_border_color)
    validate_col(get_text_border_color, data)
  }
}

# validate get_text_border_width
validate_get_text_border_width <- function(layer) {
  UseMethod("validate_get_text_border_width")
}
validate_get_text_border_width.default <- function(layer) {
  get_text_border_width <- layer$get_text_border_width
  assert_not_null(get_text_border_width)
  if (!inherits(get_text_border_width, "accessor")) {
    assert_type(get_text_border_width, c("integer", "numeric"))
    assert_finite(get_text_border_width)
    assert_scalar(get_text_border_width)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_text_border_width$col, data)
    if (!inherits(get_text_border_width, "accessor_scale")) {
      assert_type(data[[get_text_border_width$col]], c("integer", "numeric"))
      assert_finite(data[[get_text_border_width$col]])
    }
  }
  if (inherits(get_text_border_width, "accessor_scale")) {
    assert_scalable_is_numeric(get_text_border_width)
    validate_col(get_text_border_width, data)
  }
}

# validate get_text_color
validate_get_text_color <- function(layer) {
  UseMethod("validate_get_text_color")
}
validate_get_text_color.default <- function(layer) {
  get_text_color <- layer$get_text_color
  assert_not_null(get_text_color)
  if (!inherits(get_text_color, "accessor")) {
    assert_rgba(get_text_color)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_text_color$col, data)
    if (!inherits(get_text_color, "accessor_scale")) {
      assert_rgba(data[[get_text_color$col]])
    }
  }
  if (inherits(get_text_color, "accessor_scale")) {
    assert_scalable_is_color(get_text_color)
    validate_col(get_text_color, data)
  }
}

# validate get_text_pixel_offset
validate_get_text_pixel_offset <- function(layer) {
  UseMethod("validate_get_text_pixel_offset")
}
validate_get_text_pixel_offset.default <- function(layer) {
  get_text_pixel_offset <- layer$get_text_pixel_offset
  assert_not_null(get_text_pixel_offset)
  if (!inherits(get_text_pixel_offset, "accessor")) {
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_text_pixel_offset$col, data)
  }
}

# validate get_text_size
validate_get_text_size <- function(layer) {
  UseMethod("validate_get_text_size")
}
validate_get_text_size.default <- function(layer) {
  get_text_size <- layer$get_text_size
  assert_not_null(get_text_size)
  if (!inherits(get_text_size, "accessor")) {
    assert_type(get_text_size, c("integer", "numeric"))
    assert_finite(get_text_size)
    assert_scalar(get_text_size)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_text_size$col, data)
    if (!inherits(get_text_size, "accessor_scale")) {
      assert_type(data[[get_text_size$col]], c("integer", "numeric"))
      assert_finite(data[[get_text_size$col]])
    }
  }
  if (inherits(get_text_size, "accessor_scale")) {
    assert_scalable_is_numeric(get_text_size)
    validate_col(get_text_size, data)
  }
}

# validate get_tile_data
validate_get_tile_data <- function(layer) {
  UseMethod("validate_get_tile_data")
}
validate_get_tile_data.default <- function(layer) {
  get_tile_data <- layer$get_tile_data
  if (is.null(get_tile_data)) {
    return()
  }
}

# validate get_tilt
validate_get_tilt <- function(layer) {
  UseMethod("validate_get_tilt")
}
validate_get_tilt.default <- function(layer) {
  get_tilt <- layer$get_tilt
  assert_not_null(get_tilt)
  if (!inherits(get_tilt, "accessor")) {
    assert_type(get_tilt, c("integer", "numeric"))
    assert_finite(get_tilt)
    assert_scalar(get_tilt)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_tilt$col, data)

    assert_type(data[[get_tilt$col]], c("integer", "numeric"))
    assert_finite(data[[get_tilt$col]])
  }
}

# validate get_timestamps
validate_get_timestamps <- function(layer) {
  UseMethod("validate_get_timestamps")
}
validate_get_timestamps.default <- function(layer) {
  get_timestamps <- layer$get_timestamps
  assert_not_null(get_timestamps)
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_timestamps$col, data)
  }
}

# validate get_transform_matrix
validate_get_transform_matrix <- function(layer) {
  UseMethod("validate_get_transform_matrix")
}
validate_get_transform_matrix.default <- function(layer) {
  get_transform_matrix <- layer$get_transform_matrix
  if (is.null(get_transform_matrix)) {
    return()
  }
  if (!inherits(get_transform_matrix, "accessor")) {
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_transform_matrix$col, data)
  }
}

# validate get_translation
validate_get_translation <- function(layer) {
  UseMethod("validate_get_translation")
}
validate_get_translation.default <- function(layer) {
  get_translation <- layer$get_translation
  assert_not_null(get_translation)
  if (!inherits(get_translation, "accessor")) {
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_translation$col, data)
  }
}

# validate get_weight
validate_get_weight <- function(layer) {
  UseMethod("validate_get_weight")
}
validate_get_weight.default <- function(layer) {
  get_weight <- layer$get_weight
  assert_not_null(get_weight)
  if (!inherits(get_weight, "accessor")) {
    assert_type(get_weight, c("integer", "numeric"))
    assert_finite(get_weight)
    assert_scalar(get_weight)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_weight$col, data)
    if (!inherits(get_weight, "accessor_scale")) {
      assert_type(data[[get_weight$col]], c("integer", "numeric"))
      assert_finite(data[[get_weight$col]])
    }
  }
  if (inherits(get_weight, "accessor_scale")) {
    assert_scalable_is_numeric(get_weight)
    validate_col(get_weight, data)
  }
}

# validate get_width
validate_get_width <- function(layer) {
  UseMethod("validate_get_width")
}
validate_get_width.default <- function(layer) {
  get_width <- layer$get_width
  assert_not_null(get_width)
  if (!inherits(get_width, "accessor")) {
    assert_type(get_width, c("integer", "numeric"))
    assert_finite(get_width)
    assert_scalar(get_width)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(get_width$col, data)
    if (!inherits(get_width, "accessor_scale")) {
      assert_type(data[[get_width$col]], c("integer", "numeric"))
      assert_finite(data[[get_width$col]])
    }
  }
  if (inherits(get_width, "accessor_scale")) {
    assert_scalable_is_numeric(get_width)
    validate_col(get_width, data)
  }
}

# validate gpu_aggregation
validate_gpu_aggregation <- function(layer) {
  UseMethod("validate_gpu_aggregation")
}
validate_gpu_aggregation.default <- function(layer) {
  gpu_aggregation <- layer$gpu_aggregation
  assert_not_null(gpu_aggregation)
  assert_type(gpu_aggregation, "logical")
}

# validate great_circle
validate_great_circle <- function(layer) {
  UseMethod("validate_great_circle")
}
validate_great_circle.default <- function(layer) {
  great_circle <- layer$great_circle
  assert_not_null(great_circle)
  assert_type(great_circle, "logical")
}

# validate high_precision
validate_high_precision <- function(layer) {
  UseMethod("validate_high_precision")
}
validate_high_precision.default <- function(layer) {
  high_precision <- layer$high_precision
  assert_not_null(high_precision)
}

# validate highlight_color
validate_highlight_color <- function(layer) {
  UseMethod("validate_highlight_color")
}
validate_highlight_color.default <- function(layer) {
  highlight_color <- layer$highlight_color
  assert_not_null(highlight_color)
  if (!inherits(highlight_color, "accessor")) {
    assert_rgba(highlight_color)
    return()
  }
  data <- layer$data
  if (inherits(data, "data.frame")) {
    assert_col_exists(highlight_color$col, data)
    if (!inherits(highlight_color, "accessor_scale")) {
      assert_rgba(data[[highlight_color$col]])
    }
  }
  if (inherits(highlight_color, "accessor_scale")) {
    assert_scalable_is_color(highlight_color)
    validate_col(highlight_color, data)
  }
}

# validate highlighted_feature_id
validate_highlighted_feature_id <- function(layer) {
  UseMethod("validate_highlighted_feature_id")
}
validate_highlighted_feature_id.default <- function(layer) {
  highlighted_feature_id <- layer$highlighted_feature_id
  if (is.null(highlighted_feature_id)) {
    return()
  }
}

# validate icon_alpha_cutoff
validate_icon_alpha_cutoff <- function(layer) {
  UseMethod("validate_icon_alpha_cutoff")
}
validate_icon_alpha_cutoff.default <- function(layer) {
  icon_alpha_cutoff <- layer$icon_alpha_cutoff
  assert_not_null(icon_alpha_cutoff)
  assert_type(icon_alpha_cutoff, c("integer", "numeric"))
  assert_finite(icon_alpha_cutoff)
  assert_range(icon_alpha_cutoff, 0, 1)
}

# validate icon_atlas
validate_icon_atlas <- function(layer) {
  UseMethod("validate_icon_atlas")
}
validate_icon_atlas.default <- function(layer) {
  icon_atlas <- layer$icon_atlas
  if (is.null(icon_atlas)) {
    return()
  }
}

# validate icon_billboard
validate_icon_billboard <- function(layer) {
  UseMethod("validate_icon_billboard")
}
validate_icon_billboard.default <- function(layer) {
  icon_billboard <- layer$icon_billboard
  assert_not_null(icon_billboard)
  assert_type(icon_billboard, "logical")
}

# validate icon_mapping
validate_icon_mapping <- function(layer) {
  UseMethod("validate_icon_mapping")
}
validate_icon_mapping.default <- function(layer) {
  icon_mapping <- layer$icon_mapping
  assert_not_null(icon_mapping)
}

# validate icon_size_max_pixels
validate_icon_size_max_pixels <- function(layer) {
  UseMethod("validate_icon_size_max_pixels")
}
validate_icon_size_max_pixels.default <- function(layer) {
  icon_size_max_pixels <- layer$icon_size_max_pixels
  assert_not_null(icon_size_max_pixels)
  assert_type(icon_size_max_pixels, c("integer", "numeric"))
  assert_finite(icon_size_max_pixels)
  assert_range(icon_size_max_pixels, 0, NULL)
}

# validate icon_size_min_pixels
validate_icon_size_min_pixels <- function(layer) {
  UseMethod("validate_icon_size_min_pixels")
}
validate_icon_size_min_pixels.default <- function(layer) {
  icon_size_min_pixels <- layer$icon_size_min_pixels
  assert_not_null(icon_size_min_pixels)
  assert_type(icon_size_min_pixels, c("integer", "numeric"))
  assert_finite(icon_size_min_pixels)
  assert_range(icon_size_min_pixels, 0, NULL)
}

# validate icon_size_scale
validate_icon_size_scale <- function(layer) {
  UseMethod("validate_icon_size_scale")
}
validate_icon_size_scale.default <- function(layer) {
  icon_size_scale <- layer$icon_size_scale
  assert_not_null(icon_size_scale)
  assert_type(icon_size_scale, c("integer", "numeric"))
  assert_finite(icon_size_scale)
  assert_range(icon_size_scale, 0, NULL)
}

# validate icon_size_units
validate_icon_size_units <- function(layer) {
  UseMethod("validate_icon_size_units")
}
validate_icon_size_units.default <- function(layer) {
  icon_size_units <- layer$icon_size_units
  assert_not_null(icon_size_units)
}

# validate image
validate_image <- function(layer) {
  UseMethod("validate_image")
}
validate_image.default <- function(layer) {
  image <- layer$image
  if (is.null(image)) {
    return()
  }
}

# validate intensity
validate_intensity <- function(layer) {
  UseMethod("validate_intensity")
}
validate_intensity.default <- function(layer) {
  intensity <- layer$intensity
  assert_not_null(intensity)
  assert_type(intensity, c("integer", "numeric"))
  assert_finite(intensity)
  assert_range(intensity, 0, NULL)
}

# validate joint_rounded
validate_joint_rounded <- function(layer) {
  UseMethod("validate_joint_rounded")
}
validate_joint_rounded.default <- function(layer) {
  joint_rounded <- layer$joint_rounded
  assert_not_null(joint_rounded)
  assert_type(joint_rounded, "logical")
}

# validate line_billboard
validate_line_billboard <- function(layer) {
  UseMethod("validate_line_billboard")
}
validate_line_billboard.default <- function(layer) {
  line_billboard <- layer$line_billboard
  assert_not_null(line_billboard)
  assert_type(line_billboard, "logical")
}

# validate line_cap_rounded
validate_line_cap_rounded <- function(layer) {
  UseMethod("validate_line_cap_rounded")
}
validate_line_cap_rounded.default <- function(layer) {
  line_cap_rounded <- layer$line_cap_rounded
  assert_not_null(line_cap_rounded)
  assert_type(line_cap_rounded, "logical")
}

# validate line_height
validate_line_height <- function(layer) {
  UseMethod("validate_line_height")
}
validate_line_height.default <- function(layer) {
  line_height <- layer$line_height
  assert_not_null(line_height)
  assert_type(line_height, c("integer", "numeric"))
  assert_finite(line_height)
}

# validate line_joint_rounded
validate_line_joint_rounded <- function(layer) {
  UseMethod("validate_line_joint_rounded")
}
validate_line_joint_rounded.default <- function(layer) {
  line_joint_rounded <- layer$line_joint_rounded
  assert_not_null(line_joint_rounded)
  assert_type(line_joint_rounded, "logical")
}

# validate line_miter_limit
validate_line_miter_limit <- function(layer) {
  UseMethod("validate_line_miter_limit")
}
validate_line_miter_limit.default <- function(layer) {
  line_miter_limit <- layer$line_miter_limit
  assert_not_null(line_miter_limit)
  assert_type(line_miter_limit, c("integer", "numeric"))
  assert_finite(line_miter_limit)
  assert_range(line_miter_limit, 0, NULL)
}

# validate line_width_max_pixels
validate_line_width_max_pixels <- function(layer) {
  UseMethod("validate_line_width_max_pixels")
}
validate_line_width_max_pixels.default <- function(layer) {
  line_width_max_pixels <- layer$line_width_max_pixels
  assert_not_null(line_width_max_pixels)
  assert_type(line_width_max_pixels, c("integer", "numeric"))
  assert_finite(line_width_max_pixels)
  assert_range(line_width_max_pixels, 0, NULL)
}

# validate line_width_min_pixels
validate_line_width_min_pixels <- function(layer) {
  UseMethod("validate_line_width_min_pixels")
}
validate_line_width_min_pixels.default <- function(layer) {
  line_width_min_pixels <- layer$line_width_min_pixels
  assert_not_null(line_width_min_pixels)
  assert_type(line_width_min_pixels, c("integer", "numeric"))
  assert_finite(line_width_min_pixels)
  assert_range(line_width_min_pixels, 0, NULL)
}

# validate line_width_scale
validate_line_width_scale <- function(layer) {
  UseMethod("validate_line_width_scale")
}
validate_line_width_scale.default <- function(layer) {
  line_width_scale <- layer$line_width_scale
  assert_not_null(line_width_scale)
  assert_type(line_width_scale, c("integer", "numeric"))
  assert_finite(line_width_scale)
  assert_range(line_width_scale, 0, NULL)
}

# validate line_width_units
validate_line_width_units <- function(layer) {
  UseMethod("validate_line_width_units")
}
validate_line_width_units.default <- function(layer) {
  line_width_units <- layer$line_width_units
  assert_not_null(line_width_units)
}

# validate loader
validate_loader <- function(layer) {
  UseMethod("validate_loader")
}
validate_loader.default <- function(layer) {
  loader <- layer$loader
  assert_not_null(loader)
}

# validate loop_length
validate_loop_length <- function(layer) {
  UseMethod("validate_loop_length")
}
validate_loop_length.default <- function(layer) {
  loop_length <- layer$loop_length
  assert_not_null(loop_length)
  assert_type(loop_length, c("integer", "numeric"))
  assert_finite(loop_length)
  assert_range(loop_length, 0, NULL)
}

# validate lower_percentile
validate_lower_percentile <- function(layer) {
  UseMethod("validate_lower_percentile")
}
validate_lower_percentile.default <- function(layer) {
  lower_percentile <- layer$lower_percentile
  assert_not_null(lower_percentile)
  assert_type(lower_percentile, c("integer", "numeric"))
  assert_finite(lower_percentile)
  assert_range(lower_percentile, 0, 100)
}

# validate material
validate_material <- function(layer) {
  UseMethod("validate_material")
}
validate_material.default <- function(layer) {
  material <- layer$material
  assert_not_null(material)
  assert_type(material, "logical")
}

# validate max_cache_byte_size
validate_max_cache_byte_size <- function(layer) {
  UseMethod("validate_max_cache_byte_size")
}
validate_max_cache_byte_size.default <- function(layer) {
  max_cache_byte_size <- layer$max_cache_byte_size
  if (is.null(max_cache_byte_size)) {
    return()
  }
}

# validate max_cache_size
validate_max_cache_size <- function(layer) {
  UseMethod("validate_max_cache_size")
}
validate_max_cache_size.default <- function(layer) {
  max_cache_size <- layer$max_cache_size
  if (is.null(max_cache_size)) {
    return()
  }
}

# validate max_requests
validate_max_requests <- function(layer) {
  UseMethod("validate_max_requests")
}
validate_max_requests.default <- function(layer) {
  max_requests <- layer$max_requests
  assert_not_null(max_requests)
  assert_type(max_requests, c("integer", "numeric"))
  assert_finite(max_requests)
}

# validate max_width
validate_max_width <- function(layer) {
  UseMethod("validate_max_width")
}
validate_max_width.default <- function(layer) {
  max_width <- layer$max_width
  assert_not_null(max_width)
  assert_type(max_width, c("integer", "numeric"))
  assert_finite(max_width)
}

# validate max_zoom
validate_max_zoom <- function(layer) {
  UseMethod("validate_max_zoom")
}
validate_max_zoom.default <- function(layer) {
  max_zoom <- layer$max_zoom
  if (is.null(max_zoom)) {
    return()
  }
}

# validate mesh
validate_mesh <- function(layer) {
  UseMethod("validate_mesh")
}
validate_mesh.default <- function(layer) {
  mesh <- layer$mesh
  if (is.null(mesh)) {
    return()
  }
}

# validate mesh_max_error
validate_mesh_max_error <- function(layer) {
  UseMethod("validate_mesh_max_error")
}
validate_mesh_max_error.default <- function(layer) {
  mesh_max_error <- layer$mesh_max_error
  assert_not_null(mesh_max_error)
  assert_type(mesh_max_error, c("integer", "numeric"))
  assert_finite(mesh_max_error)
}

# validate min_zoom
validate_min_zoom <- function(layer) {
  UseMethod("validate_min_zoom")
}
validate_min_zoom.default <- function(layer) {
  min_zoom <- layer$min_zoom
  assert_not_null(min_zoom)
  assert_type(min_zoom, c("integer", "numeric"))
  assert_finite(min_zoom)
}

# validate miter_limit
validate_miter_limit <- function(layer) {
  UseMethod("validate_miter_limit")
}
validate_miter_limit.default <- function(layer) {
  miter_limit <- layer$miter_limit
  assert_not_null(miter_limit)
  assert_type(miter_limit, c("integer", "numeric"))
  assert_finite(miter_limit)
  assert_range(miter_limit, 0, NULL)
}

# validate offset
validate_offset <- function(layer) {
  UseMethod("validate_offset")
}
validate_offset.default <- function(layer) {
  offset <- layer$offset
  assert_not_null(offset)
}

# validate opacity
validate_opacity <- function(layer) {
  UseMethod("validate_opacity")
}
validate_opacity.default <- function(layer) {
  opacity <- layer$opacity
  assert_not_null(opacity)
  assert_type(opacity, c("integer", "numeric"))
  assert_finite(opacity)
  assert_range(opacity, 0, 1)
}

# validate outline_color
validate_outline_color <- function(layer) {
  UseMethod("validate_outline_color")
}
validate_outline_color.default <- function(layer) {
  outline_color <- layer$outline_color
  assert_not_null(outline_color)
  assert_rgba(outline_color)
}

# validate outline_width
validate_outline_width <- function(layer) {
  UseMethod("validate_outline_width")
}
validate_outline_width.default <- function(layer) {
  outline_width <- layer$outline_width
  assert_not_null(outline_width)
  assert_type(outline_width, c("integer", "numeric"))
  assert_finite(outline_width)
  assert_range(outline_width, 0, NULL)
}

# validate pickable
validate_pickable <- function(layer) {
  UseMethod("validate_pickable")
}
validate_pickable.default <- function(layer) {
  pickable <- layer$pickable
  assert_not_null(pickable)
  assert_type(pickable, "logical")
}

# validate point_antialiasing
validate_point_antialiasing <- function(layer) {
  UseMethod("validate_point_antialiasing")
}
validate_point_antialiasing.default <- function(layer) {
  point_antialiasing <- layer$point_antialiasing
  assert_not_null(point_antialiasing)
  assert_type(point_antialiasing, "logical")
}

# validate point_billboard
validate_point_billboard <- function(layer) {
  UseMethod("validate_point_billboard")
}
validate_point_billboard.default <- function(layer) {
  point_billboard <- layer$point_billboard
  assert_not_null(point_billboard)
  assert_type(point_billboard, "logical")
}

# validate point_radius_max_pixels
validate_point_radius_max_pixels <- function(layer) {
  UseMethod("validate_point_radius_max_pixels")
}
validate_point_radius_max_pixels.default <- function(layer) {
  point_radius_max_pixels <- layer$point_radius_max_pixels
  assert_not_null(point_radius_max_pixels)
  assert_type(point_radius_max_pixels, c("integer", "numeric"))
  assert_finite(point_radius_max_pixels)
  assert_range(point_radius_max_pixels, 0, NULL)
}

# validate point_radius_min_pixels
validate_point_radius_min_pixels <- function(layer) {
  UseMethod("validate_point_radius_min_pixels")
}
validate_point_radius_min_pixels.default <- function(layer) {
  point_radius_min_pixels <- layer$point_radius_min_pixels
  assert_not_null(point_radius_min_pixels)
  assert_type(point_radius_min_pixels, c("integer", "numeric"))
  assert_finite(point_radius_min_pixels)
  assert_range(point_radius_min_pixels, 0, NULL)
}

# validate point_radius_scale
validate_point_radius_scale <- function(layer) {
  UseMethod("validate_point_radius_scale")
}
validate_point_radius_scale.default <- function(layer) {
  point_radius_scale <- layer$point_radius_scale
  assert_not_null(point_radius_scale)
  assert_type(point_radius_scale, c("integer", "numeric"))
  assert_finite(point_radius_scale)
  assert_range(point_radius_scale, 0, NULL)
}

# validate point_radius_units
validate_point_radius_units <- function(layer) {
  UseMethod("validate_point_radius_units")
}
validate_point_radius_units.default <- function(layer) {
  point_radius_units <- layer$point_radius_units
  assert_not_null(point_radius_units)
}

# validate point_size
validate_point_size <- function(layer) {
  UseMethod("validate_point_size")
}
validate_point_size.default <- function(layer) {
  point_size <- layer$point_size
  assert_not_null(point_size)
  assert_type(point_size, c("integer", "numeric"))
  assert_finite(point_size)
}

# validate point_type
validate_point_type <- function(layer) {
  UseMethod("validate_point_type")
}
validate_point_type.default <- function(layer) {
  point_type <- layer$point_type
  assert_not_null(point_type)
}

# validate position_format
validate_position_format <- function(layer) {
  UseMethod("validate_position_format")
}
validate_position_format.default <- function(layer) {
  position_format <- layer$position_format
  assert_not_null(position_format)
}

# validate radius
validate_radius <- function(layer) {
  UseMethod("validate_radius")
}
validate_radius.default <- function(layer) {
  radius <- layer$radius
  assert_not_null(radius)
  assert_type(radius, c("integer", "numeric"))
  assert_finite(radius)
  assert_range(radius, 1, NULL)
}

# validate radius_max_pixels
validate_radius_max_pixels <- function(layer) {
  UseMethod("validate_radius_max_pixels")
}
validate_radius_max_pixels.default <- function(layer) {
  radius_max_pixels <- layer$radius_max_pixels
  assert_not_null(radius_max_pixels)
  assert_type(radius_max_pixels, c("integer", "numeric"))
  assert_finite(radius_max_pixels)
  assert_range(radius_max_pixels, 0, NULL)
}

# validate radius_min_pixels
validate_radius_min_pixels <- function(layer) {
  UseMethod("validate_radius_min_pixels")
}
validate_radius_min_pixels.default <- function(layer) {
  radius_min_pixels <- layer$radius_min_pixels
  assert_not_null(radius_min_pixels)
  assert_type(radius_min_pixels, c("integer", "numeric"))
  assert_finite(radius_min_pixels)
  assert_range(radius_min_pixels, 0, NULL)
}

# validate radius_pixels
validate_radius_pixels <- function(layer) {
  UseMethod("validate_radius_pixels")
}
validate_radius_pixels.default <- function(layer) {
  radius_pixels <- layer$radius_pixels
  assert_not_null(radius_pixels)
  assert_type(radius_pixels, c("integer", "numeric"))
  assert_finite(radius_pixels)
  assert_range(radius_pixels, 1, 100)
}

# validate radius_scale
validate_radius_scale <- function(layer) {
  UseMethod("validate_radius_scale")
}
validate_radius_scale.default <- function(layer) {
  radius_scale <- layer$radius_scale
  assert_not_null(radius_scale)
  assert_type(radius_scale, c("integer", "numeric"))
  assert_finite(radius_scale)
  assert_range(radius_scale, 0, NULL)
}

# validate radius_units
validate_radius_units <- function(layer) {
  UseMethod("validate_radius_units")
}
validate_radius_units.default <- function(layer) {
  radius_units <- layer$radius_units
  assert_not_null(radius_units)
}

# validate refinement_strategy
validate_refinement_strategy <- function(layer) {
  UseMethod("validate_refinement_strategy")
}
validate_refinement_strategy.default <- function(layer) {
  refinement_strategy <- layer$refinement_strategy
  assert_not_null(refinement_strategy)
}

# validate scenegraph
validate_scenegraph <- function(layer) {
  UseMethod("validate_scenegraph")
}
validate_scenegraph.default <- function(layer) {
  scenegraph <- layer$scenegraph
  if (is.null(scenegraph)) {
    return()
  }
}

# validate size_max_pixels
validate_size_max_pixels <- function(layer) {
  UseMethod("validate_size_max_pixels")
}
validate_size_max_pixels.default <- function(layer) {
  size_max_pixels <- layer$size_max_pixels
  assert_not_null(size_max_pixels)
  assert_type(size_max_pixels, c("integer", "numeric"))
  assert_finite(size_max_pixels)
  assert_range(size_max_pixels, 0, NULL)
}

# validate size_min_pixels
validate_size_min_pixels <- function(layer) {
  UseMethod("validate_size_min_pixels")
}
validate_size_min_pixels.default <- function(layer) {
  size_min_pixels <- layer$size_min_pixels
  assert_not_null(size_min_pixels)
  assert_type(size_min_pixels, c("integer", "numeric"))
  assert_finite(size_min_pixels)
  assert_range(size_min_pixels, 0, NULL)
}

# validate size_scale
validate_size_scale <- function(layer) {
  UseMethod("validate_size_scale")
}
validate_size_scale.default <- function(layer) {
  size_scale <- layer$size_scale
  assert_not_null(size_scale)
  assert_type(size_scale, c("integer", "numeric"))
  assert_finite(size_scale)
  assert_range(size_scale, 0, NULL)
}

# validate size_units
validate_size_units <- function(layer) {
  UseMethod("validate_size_units")
}
validate_size_units.default <- function(layer) {
  size_units <- layer$size_units
  assert_not_null(size_units)
}

# validate stroked
validate_stroked <- function(layer) {
  UseMethod("validate_stroked")
}
validate_stroked.default <- function(layer) {
  stroked <- layer$stroked
  assert_not_null(stroked)
  assert_type(stroked, "logical")
}

# validate text_background
validate_text_background <- function(layer) {
  UseMethod("validate_text_background")
}
validate_text_background.default <- function(layer) {
  text_background <- layer$text_background
  assert_not_null(text_background)
  assert_type(text_background, "logical")
}

# validate text_background_padding
validate_text_background_padding <- function(layer) {
  UseMethod("validate_text_background_padding")
}
validate_text_background_padding.default <- function(layer) {
  text_background_padding <- layer$text_background_padding
  assert_not_null(text_background_padding)
}

# validate text_billboard
validate_text_billboard <- function(layer) {
  UseMethod("validate_text_billboard")
}
validate_text_billboard.default <- function(layer) {
  text_billboard <- layer$text_billboard
  assert_not_null(text_billboard)
  assert_type(text_billboard, "logical")
}

# validate text_font_family
validate_text_font_family <- function(layer) {
  UseMethod("validate_text_font_family")
}
validate_text_font_family.default <- function(layer) {
  text_font_family <- layer$text_font_family
  assert_not_null(text_font_family)
}

# validate text_font_settings
validate_text_font_settings <- function(layer) {
  UseMethod("validate_text_font_settings")
}
validate_text_font_settings.default <- function(layer) {
  text_font_settings <- layer$text_font_settings
  assert_not_null(text_font_settings)
}

# validate text_font_weight
validate_text_font_weight <- function(layer) {
  UseMethod("validate_text_font_weight")
}
validate_text_font_weight.default <- function(layer) {
  text_font_weight <- layer$text_font_weight
  assert_not_null(text_font_weight)
}

# validate text_line_height
validate_text_line_height <- function(layer) {
  UseMethod("validate_text_line_height")
}
validate_text_line_height.default <- function(layer) {
  text_line_height <- layer$text_line_height
  assert_not_null(text_line_height)
  assert_type(text_line_height, c("integer", "numeric"))
  assert_finite(text_line_height)
}

# validate text_max_width
validate_text_max_width <- function(layer) {
  UseMethod("validate_text_max_width")
}
validate_text_max_width.default <- function(layer) {
  text_max_width <- layer$text_max_width
  assert_not_null(text_max_width)
  assert_type(text_max_width, c("integer", "numeric"))
  assert_finite(text_max_width)
}

# validate text_outline_color
validate_text_outline_color <- function(layer) {
  UseMethod("validate_text_outline_color")
}
validate_text_outline_color.default <- function(layer) {
  text_outline_color <- layer$text_outline_color
  assert_not_null(text_outline_color)
  assert_rgba(text_outline_color)
}

# validate text_outline_width
validate_text_outline_width <- function(layer) {
  UseMethod("validate_text_outline_width")
}
validate_text_outline_width.default <- function(layer) {
  text_outline_width <- layer$text_outline_width
  assert_not_null(text_outline_width)
  assert_type(text_outline_width, c("integer", "numeric"))
  assert_finite(text_outline_width)
  assert_range(text_outline_width, 0, NULL)
}

# validate text_size_max_pixels
validate_text_size_max_pixels <- function(layer) {
  UseMethod("validate_text_size_max_pixels")
}
validate_text_size_max_pixels.default <- function(layer) {
  text_size_max_pixels <- layer$text_size_max_pixels
  assert_not_null(text_size_max_pixels)
  assert_type(text_size_max_pixels, c("integer", "numeric"))
  assert_finite(text_size_max_pixels)
}

# validate text_size_min_pixels
validate_text_size_min_pixels <- function(layer) {
  UseMethod("validate_text_size_min_pixels")
}
validate_text_size_min_pixels.default <- function(layer) {
  text_size_min_pixels <- layer$text_size_min_pixels
  assert_not_null(text_size_min_pixels)
  assert_type(text_size_min_pixels, c("integer", "numeric"))
  assert_finite(text_size_min_pixels)
}

# validate text_size_scale
validate_text_size_scale <- function(layer) {
  UseMethod("validate_text_size_scale")
}
validate_text_size_scale.default <- function(layer) {
  text_size_scale <- layer$text_size_scale
  assert_not_null(text_size_scale)
  assert_type(text_size_scale, c("integer", "numeric"))
  assert_finite(text_size_scale)
}

# validate text_size_units
validate_text_size_units <- function(layer) {
  UseMethod("validate_text_size_units")
}
validate_text_size_units.default <- function(layer) {
  text_size_units <- layer$text_size_units
  assert_not_null(text_size_units)
}

# validate text_word_break
validate_text_word_break <- function(layer) {
  UseMethod("validate_text_word_break")
}
validate_text_word_break.default <- function(layer) {
  text_word_break <- layer$text_word_break
  assert_not_null(text_word_break)
}

# validate texture
validate_texture <- function(layer) {
  UseMethod("validate_texture")
}
validate_texture.default <- function(layer) {
  texture <- layer$texture
  if (is.null(texture)) {
    return()
  }
}

# validate threshold
validate_threshold <- function(layer) {
  UseMethod("validate_threshold")
}
validate_threshold.default <- function(layer) {
  threshold <- layer$threshold
  assert_not_null(threshold)
  assert_type(threshold, c("integer", "numeric"))
  assert_finite(threshold)
  assert_range(threshold, 0, 1)
}

# validate tile_size
validate_tile_size <- function(layer) {
  UseMethod("validate_tile_size")
}
validate_tile_size.default <- function(layer) {
  tile_size <- layer$tile_size
  assert_not_null(tile_size)
  assert_type(tile_size, c("integer", "numeric"))
  assert_finite(tile_size)
}

# validate tint_color
validate_tint_color <- function(layer) {
  UseMethod("validate_tint_color")
}
validate_tint_color.default <- function(layer) {
  tint_color <- layer$tint_color
  assert_not_null(tint_color)
  assert_rgba(tint_color)
}

# validate trail_length
validate_trail_length <- function(layer) {
  UseMethod("validate_trail_length")
}
validate_trail_length.default <- function(layer) {
  trail_length <- layer$trail_length
  assert_not_null(trail_length)
  assert_type(trail_length, c("integer", "numeric"))
  assert_finite(trail_length)
  assert_range(trail_length, 0, NULL)
}

# validate transparent_color
validate_transparent_color <- function(layer) {
  UseMethod("validate_transparent_color")
}
validate_transparent_color.default <- function(layer) {
  transparent_color <- layer$transparent_color
  assert_not_null(transparent_color)
  assert_rgba(transparent_color)
}

# validate unique_id_property
validate_unique_id_property <- function(layer) {
  UseMethod("validate_unique_id_property")
}
validate_unique_id_property.default <- function(layer) {
  unique_id_property <- layer$unique_id_property
  assert_not_null(unique_id_property)
  assert_type(unique_id_property, "character")
}

# validate upper_percentile
validate_upper_percentile <- function(layer) {
  UseMethod("validate_upper_percentile")
}
validate_upper_percentile.default <- function(layer) {
  upper_percentile <- layer$upper_percentile
  assert_not_null(upper_percentile)
  assert_type(upper_percentile, c("integer", "numeric"))
  assert_finite(upper_percentile)
  assert_range(upper_percentile, 0, 100)
}

# validate vertices
validate_vertices <- function(layer) {
  UseMethod("validate_vertices")
}
validate_vertices.default <- function(layer) {
  vertices <- layer$vertices
  if (is.null(vertices)) {
    return()
  }
}

# validate visible
validate_visible <- function(layer) {
  UseMethod("validate_visible")
}
validate_visible.default <- function(layer) {
  visible <- layer$visible
  if (is.null(visible)) {
    return()
  }
  assert_type(visible, "logical")
}

# validate weights_texture_size
validate_weights_texture_size <- function(layer) {
  UseMethod("validate_weights_texture_size")
}
validate_weights_texture_size.default <- function(layer) {
  weights_texture_size <- layer$weights_texture_size
  assert_not_null(weights_texture_size)
  assert_type(weights_texture_size, c("integer", "numeric"))
  assert_finite(weights_texture_size)
  assert_range(weights_texture_size, 128, 2048)
}

# validate width_max_pixels
validate_width_max_pixels <- function(layer) {
  UseMethod("validate_width_max_pixels")
}
validate_width_max_pixels.default <- function(layer) {
  width_max_pixels <- layer$width_max_pixels
  assert_not_null(width_max_pixels)
  assert_type(width_max_pixels, c("integer", "numeric"))
  assert_finite(width_max_pixels)
  assert_range(width_max_pixels, 0, NULL)
}

# validate width_min_pixels
validate_width_min_pixels <- function(layer) {
  UseMethod("validate_width_min_pixels")
}
validate_width_min_pixels.default <- function(layer) {
  width_min_pixels <- layer$width_min_pixels
  assert_not_null(width_min_pixels)
  assert_type(width_min_pixels, c("integer", "numeric"))
  assert_finite(width_min_pixels)
  assert_range(width_min_pixels, 0, NULL)
}

# validate width_scale
validate_width_scale <- function(layer) {
  UseMethod("validate_width_scale")
}
validate_width_scale.default <- function(layer) {
  width_scale <- layer$width_scale
  assert_not_null(width_scale)
  assert_type(width_scale, c("integer", "numeric"))
  assert_finite(width_scale)
  assert_range(width_scale, 0, NULL)
}

# validate width_units
validate_width_units <- function(layer) {
  UseMethod("validate_width_units")
}
validate_width_units.default <- function(layer) {
  width_units <- layer$width_units
  assert_not_null(width_units)
}

# validate wireframe
validate_wireframe <- function(layer) {
  UseMethod("validate_wireframe")
}
validate_wireframe.default <- function(layer) {
  wireframe <- layer$wireframe
  assert_not_null(wireframe)
  assert_type(wireframe, "logical")
}

# validate word_break
validate_word_break <- function(layer) {
  UseMethod("validate_word_break")
}
validate_word_break.default <- function(layer) {
  word_break <- layer$word_break
  assert_not_null(word_break)
}

# validate worker_url
validate_worker_url <- function(layer) {
  UseMethod("validate_worker_url")
}
validate_worker_url.default <- function(layer) {
  worker_url <- layer$worker_url
  if (is.null(worker_url)) {
    return()
  }
  assert_type(worker_url, "character")
}

# validate wrap_longitude
validate_wrap_longitude <- function(layer) {
  UseMethod("validate_wrap_longitude")
}
validate_wrap_longitude.default <- function(layer) {
  wrap_longitude <- layer$wrap_longitude
  assert_not_null(wrap_longitude)
  assert_type(wrap_longitude, "logical")
}

# validate z_offset
validate_z_offset <- function(layer) {
  UseMethod("validate_z_offset")
}
validate_z_offset.default <- function(layer) {
  z_offset <- layer$z_offset
  assert_not_null(z_offset)
  assert_type(z_offset, c("integer", "numeric"))
  assert_finite(z_offset)
}

# validate z_range
validate_z_range <- function(layer) {
  UseMethod("validate_z_range")
}
validate_z_range.default <- function(layer) {
  z_range <- layer$z_range
  if (is.null(z_range)) {
    return()
  }
}

# validate zoom_offset
validate_zoom_offset <- function(layer) {
  UseMethod("validate_zoom_offset")
}
validate_zoom_offset.default <- function(layer) {
  zoom_offset <- layer$zoom_offset
  assert_not_null(zoom_offset)
  assert_type(zoom_offset, c("integer", "numeric"))
  assert_finite(zoom_offset)
}
