# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "source_position", # <add_arc_layer>
  "target_position", # <add_arc_layer>
  "position", # <add_icon_layer>
  "icon", # <add_icon_layer>
  "source_position", # <add_line_layer>
  "target_position", # <add_line_layer>
  "position", # <add_point_cloud_layer>
  "position", # <add_scatterplot_layer>
  "position", # <add_grid_cell_layer>
  "position", # <add_column_layer>
  "path", # <add_path_layer>
  "polygon", # <add_polygon_layer>
  "polygon", # <add_solid_polygon_layer>
  "text", # <add_text_layer>
  "position", # <add_text_layer>
  "position", # <add_screen_grid_layer>
  "position", # <add_cpu_grid_layer>
  "position", # <add_hexagon_layer>
  "position", # <add_contour_layer>
  "position", # <add_grid_layer>
  "position", # <add_gpu_grid_layer>
  "position", # <add_heatmap_layer>
  "source_position", # <add_great_circle_layer>
  "target_position", # <add_great_circle_layer>
  "token", # <add_s2_layer>
  "hexagons", # <add_h3_cluster_layer>
  "hexagon", # <add_h3_hexagon_layer>
  "path", # <add_trips_layer>
  "timestamps", # <add_trips_layer>
  "position", # <add_simple_mesh_layer>
  "position", # <add_scenegraph_layer>
  NULL
))
